/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loop;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Frank
 */
public class add_remove_roomTypes extends javax.swing.JFrame {

     public Connection cn;
    public Statement st;
    /*public void conection() {

        try {
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loop_hotel?zeroDateTimeBehavior=convertToNull", "root", "");
            st = cn.createStatement();
            System.out.println("conected");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "not conected");
        }
    }*/
    
    public void RoomType_combobox()
    {
         try{
             RoomType_combobox.removeAllItems();
            String sql = ("SELECT `Room_type` FROM `rooms`  ");
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {
                
                String top = rs.getString("Room_type");
                System.out.println(top);
                RoomType_combobox.addItem(top);
            }
        }
        catch(SQLException e){ System.out.println(e);}
    }
    
    public void return_(){Add_Room_Type_pane.setVisible(false);
                     remove_roomType_pane.setVisible(true);}
    
    
     public void update()
    {
        get_set_data pop = new get_set_data();
        pop.main(cn);
        System.out.println("Done");
    } 
     
    public add_remove_roomTypes() {
        initComponents();
        this.setLocationRelativeTo(null);
        error1_lable.setVisible(false);
        error2_lable.setVisible(false);
        Add_Room_Type_pane.setVisible(true);
        remove_roomType_pane.setVisible(false);
        RoomType_combobox();
        update();
        
    }
    public add_remove_roomTypes(Connection con) {
        initComponents();
        this.setLocationRelativeTo(null);
        cn = con;
        error1_lable.setVisible(false);
        error2_lable.setVisible(false);
        Add_Room_Type_pane.setVisible(true);
        remove_roomType_pane.setVisible(false);
        RoomType_combobox();
        update();
        
    }
    public add_remove_roomTypes(Connection con, boolean t) {
        initComponents();
        this.setLocationRelativeTo(null);
        cn = con;
        error1_lable.setVisible(false);
        error2_lable.setVisible(false);
        Add_Room_Type_pane.setVisible(true);
        remove_roomType_pane.setVisible(false);
        RoomType_combobox();
        update();
        if(t){return_();}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        style1_pane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        hotel_lable = new javax.swing.JLabel();
        hotel_lable1 = new javax.swing.JLabel();
        addRoomType_button = new javax.swing.JButton();
        removeRoomType_button = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        maste_pane = new javax.swing.JLayeredPane();
        Add_Room_Type_pane = new javax.swing.JPanel();
        roomName_lable = new javax.swing.JLabel();
        roomTypeName_textbox = new javax.swing.JTextField();
        costPerNight_lable = new javax.swing.JLabel();
        costPerNight_textbox = new javax.swing.JTextField();
        adRoomType_button_inpane = new javax.swing.JButton();
        error1_lable = new javax.swing.JLabel();
        error2_lable = new javax.swing.JLabel();
        remove_roomType_pane = new javax.swing.JPanel();
        roomNameToRemove_lable = new javax.swing.JLabel();
        RoomType_combobox = new javax.swing.JComboBox<>();
        deleteRoomType_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        style1_pane.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        hotel_lable.setBackground(new java.awt.Color(0, 204, 255));
        hotel_lable.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        hotel_lable.setForeground(new java.awt.Color(255, 255, 255));
        hotel_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotel_lable.setText("Hotel");
        hotel_lable.setToolTipText("");

        hotel_lable1.setBackground(new java.awt.Color(0, 204, 255));
        hotel_lable1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        hotel_lable1.setForeground(new java.awt.Color(255, 255, 255));
        hotel_lable1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotel_lable1.setText("Reservation");
        hotel_lable1.setToolTipText("");

        addRoomType_button.setBackground(new java.awt.Color(255, 255, 255));
        addRoomType_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addRoomType_button.setForeground(new java.awt.Color(51, 102, 255));
        addRoomType_button.setText("Add RoomType");
        addRoomType_button.setToolTipText("");
        addRoomType_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomType_buttonActionPerformed(evt);
            }
        });

        removeRoomType_button.setBackground(new java.awt.Color(255, 255, 255));
        removeRoomType_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        removeRoomType_button.setForeground(new java.awt.Color(51, 102, 255));
        removeRoomType_button.setText("Remove RoomType");
        removeRoomType_button.setToolTipText("");
        removeRoomType_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRoomType_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addRoomType_button, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hotel_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(removeRoomType_button))
                            .addComponent(hotel_lable1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(hotel_lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hotel_lable1)
                .addGap(39, 39, 39)
                .addComponent(addRoomType_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeRoomType_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        closeButton.setBackground(new java.awt.Color(0, 102, 255));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("X");
        closeButton.setToolTipText("");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        Add_Room_Type_pane.setBackground(new java.awt.Color(255, 255, 255));

        roomName_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        roomName_lable.setForeground(new java.awt.Color(51, 102, 255));
        roomName_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roomName_lable.setText("Room Type Name");

        roomTypeName_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        roomTypeName_textbox.setForeground(new java.awt.Color(51, 102, 255));
        roomTypeName_textbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomTypeName_textboxMouseClicked(evt);
            }
        });
        roomTypeName_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypeName_textboxActionPerformed(evt);
            }
        });

        costPerNight_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        costPerNight_lable.setForeground(new java.awt.Color(51, 102, 255));
        costPerNight_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        costPerNight_lable.setText("Cost per Night");

        costPerNight_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        costPerNight_textbox.setForeground(new java.awt.Color(51, 102, 255));
        costPerNight_textbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                costPerNight_textboxMouseClicked(evt);
            }
        });
        costPerNight_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costPerNight_textboxActionPerformed(evt);
            }
        });

        adRoomType_button_inpane.setBackground(new java.awt.Color(51, 102, 255));
        adRoomType_button_inpane.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adRoomType_button_inpane.setForeground(new java.awt.Color(255, 255, 255));
        adRoomType_button_inpane.setText("Add");
        adRoomType_button_inpane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adRoomType_button_inpaneActionPerformed(evt);
            }
        });

        error1_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        error1_lable.setForeground(new java.awt.Color(255, 0, 0));
        error1_lable.setText("*");

        error2_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        error2_lable.setForeground(new java.awt.Color(255, 0, 0));
        error2_lable.setText("*");

        javax.swing.GroupLayout Add_Room_Type_paneLayout = new javax.swing.GroupLayout(Add_Room_Type_pane);
        Add_Room_Type_pane.setLayout(Add_Room_Type_paneLayout);
        Add_Room_Type_paneLayout.setHorizontalGroup(
            Add_Room_Type_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_Room_Type_paneLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(Add_Room_Type_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adRoomType_button_inpane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Add_Room_Type_paneLayout.createSequentialGroup()
                        .addComponent(costPerNight_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(error2_lable))
                    .addComponent(costPerNight_lable)
                    .addGroup(Add_Room_Type_paneLayout.createSequentialGroup()
                        .addComponent(roomTypeName_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(error1_lable))
                    .addComponent(roomName_lable))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        Add_Room_Type_paneLayout.setVerticalGroup(
            Add_Room_Type_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_Room_Type_paneLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(roomName_lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Add_Room_Type_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomTypeName_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error1_lable))
                .addGap(18, 18, 18)
                .addComponent(costPerNight_lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Add_Room_Type_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costPerNight_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error2_lable))
                .addGap(44, 44, 44)
                .addComponent(adRoomType_button_inpane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        remove_roomType_pane.setBackground(new java.awt.Color(255, 255, 255));
        remove_roomType_pane.setPreferredSize(new java.awt.Dimension(382, 451));

        roomNameToRemove_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        roomNameToRemove_lable.setForeground(new java.awt.Color(51, 102, 255));
        roomNameToRemove_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roomNameToRemove_lable.setText("Room Type Name");

        RoomType_combobox.setBackground(new java.awt.Color(51, 102, 255));
        RoomType_combobox.setForeground(new java.awt.Color(255, 255, 255));
        RoomType_combobox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomType_comboboxMouseClicked(evt);
            }
        });
        RoomType_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomType_comboboxActionPerformed(evt);
            }
        });

        deleteRoomType_button.setBackground(new java.awt.Color(255, 0, 0));
        deleteRoomType_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteRoomType_button.setForeground(new java.awt.Color(255, 255, 255));
        deleteRoomType_button.setText("Delete");
        deleteRoomType_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRoomType_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout remove_roomType_paneLayout = new javax.swing.GroupLayout(remove_roomType_pane);
        remove_roomType_pane.setLayout(remove_roomType_paneLayout);
        remove_roomType_paneLayout.setHorizontalGroup(
            remove_roomType_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remove_roomType_paneLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(remove_roomType_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteRoomType_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomType_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomNameToRemove_lable))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        remove_roomType_paneLayout.setVerticalGroup(
            remove_roomType_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remove_roomType_paneLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(roomNameToRemove_lable)
                .addGap(26, 26, 26)
                .addComponent(RoomType_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(deleteRoomType_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        maste_pane.setLayer(Add_Room_Type_pane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        maste_pane.setLayer(remove_roomType_pane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout maste_paneLayout = new javax.swing.GroupLayout(maste_pane);
        maste_pane.setLayout(maste_paneLayout);
        maste_paneLayout.setHorizontalGroup(
            maste_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add_Room_Type_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(maste_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(remove_roomType_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
        );
        maste_paneLayout.setVerticalGroup(
            maste_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add_Room_Type_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(maste_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(remove_roomType_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout style1_paneLayout = new javax.swing.GroupLayout(style1_pane);
        style1_pane.setLayout(style1_paneLayout);
        style1_paneLayout.setHorizontalGroup(
            style1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(style1_paneLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(style1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(style1_paneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(maste_pane)))
        );
        style1_paneLayout.setVerticalGroup(
            style1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(style1_paneLayout.createSequentialGroup()
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maste_pane))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(style1_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(style1_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        update();
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void addRoomType_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomType_buttonActionPerformed
        // TODO add your handling code here:
        update();
        Add_Room_Type_pane.setVisible(true);
        remove_roomType_pane.setVisible(false);
        
    }//GEN-LAST:event_addRoomType_buttonActionPerformed

    private void removeRoomType_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRoomType_buttonActionPerformed
        // TODO add your handling code here:
        update();
        Add_Room_Type_pane.setVisible(false);
        remove_roomType_pane.setVisible(true);
    }//GEN-LAST:event_removeRoomType_buttonActionPerformed

    private void adRoomType_button_inpaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adRoomType_button_inpaneActionPerformed
        // TODO add your handling code here:
        String roomTypeName = roomTypeName_textbox.getText();
        String costPerNight = costPerNight_textbox.getText();
        if(roomTypeName.equals("")){error1_lable.setVisible(true);}
        if(costPerNight.equals("")){error2_lable.setVisible(true);}
        if(roomTypeName.equals("")==false && costPerNight.equals("")== false )
        {
            try {
                
                String sql = "INSERT INTO `rooms`(`Room_type`, `cost_per_night`) VALUES ('"+roomTypeName+"','"+costPerNight+"')";
                PreparedStatement ps = cn.prepareStatement(sql);
                int rs = ps.executeUpdate();
                if(rs > 0  ){JOptionPane.showMessageDialog(null, "submitted");}
                error1_lable.setVisible(false);
                error2_lable.setVisible(false);
                roomTypeName_textbox.setText("");
                costPerNight_textbox.setText("");
                RoomType_combobox();

                

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        update();
    }//GEN-LAST:event_adRoomType_button_inpaneActionPerformed

    private void costPerNight_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costPerNight_textboxActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_costPerNight_textboxActionPerformed

    private void roomTypeName_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeName_textboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomTypeName_textboxActionPerformed

    private void costPerNight_textboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_costPerNight_textboxMouseClicked
        // TODO add your handling code here:
        error2_lable.setVisible(false);
    }//GEN-LAST:event_costPerNight_textboxMouseClicked

    private void roomTypeName_textboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomTypeName_textboxMouseClicked
        // TODO add your handling code here:
        error1_lable.setVisible(false);
    }//GEN-LAST:event_roomTypeName_textboxMouseClicked

    private void RoomType_comboboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomType_comboboxMouseClicked

    }//GEN-LAST:event_RoomType_comboboxMouseClicked

    private void RoomType_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomType_comboboxActionPerformed

    }//GEN-LAST:event_RoomType_comboboxActionPerformed

    private void deleteRoomType_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRoomType_buttonActionPerformed
        // TODO add your handling code here:
        String roomTypeName = String.valueOf(RoomType_combobox.getSelectedItem());
        new Delete_RoomType_confirmation(roomTypeName, cn).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deleteRoomType_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_remove_roomTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_remove_roomTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_remove_roomTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_remove_roomTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_remove_roomTypes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add_Room_Type_pane;
    private javax.swing.JComboBox<String> RoomType_combobox;
    private javax.swing.JButton adRoomType_button_inpane;
    private javax.swing.JButton addRoomType_button;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel costPerNight_lable;
    private javax.swing.JTextField costPerNight_textbox;
    private javax.swing.JButton deleteRoomType_button;
    private javax.swing.JLabel error1_lable;
    private javax.swing.JLabel error2_lable;
    private javax.swing.JLabel hotel_lable;
    private javax.swing.JLabel hotel_lable1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane maste_pane;
    private javax.swing.JButton removeRoomType_button;
    private javax.swing.JPanel remove_roomType_pane;
    private javax.swing.JLabel roomNameToRemove_lable;
    private javax.swing.JLabel roomName_lable;
    private javax.swing.JTextField roomTypeName_textbox;
    private javax.swing.JPanel style1_pane;
    // End of variables declaration//GEN-END:variables
}
