/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loop;

import java.awt.Image;
import static java.lang.String.format;
import java.sql.*;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Frank
 */
public class Booking_delete_confirm extends javax.swing.JFrame {

    public Connection cn;
    public Statement st;
    public byte[] image_indentification= null;
    
    /*public void conection()    
    {    
        
       try
        {
             cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loop_hotel?zeroDateTimeBehavior=convertToNull", "root","");
             st = cn.createStatement();
             System.out.println("conected");
            
        }
        catch(SQLException e )
        {
            JOptionPane.showMessageDialog(null,"not conected" );
        }
    }*/
    
    /// display all the details 
    public void display_deatils(String booking_ind )
    {
        try 
        {
            String sql = "SELECT * FROM `bookings` WHERE `Ind_book` = '"+booking_ind+"'";
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {
                firstname_textbox.setText(rs.getString("Booked_by_firstname"));
                lastname_textbox.setText(rs.getString("Booked_by_lastname"));
                dateFrom_textbox.setText(rs.getString("Booked_from"));
                dateTo_textbox.setText(rs.getString("Booked_to"));
                noAdult_textbox.setText(rs.getString("No. of Adults"));
                noChildren_textbox.setText(rs.getString("No. of children"));
                
                byte[] img= rs.getBytes("identification");
                System.out.println(Arrays.toString(img));
                image_indentification= img;
                ImageIcon image = new ImageIcon(img);
                Image im  = image.getImage();
                Image myimg = im.getScaledInstance(icon.getWidth(), icon.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newimage = new ImageIcon(myimg);
                System.out.println(newimage);
                icon.setIcon(newimage);
            }
        }
        catch(SQLException e )
        {System.out.println("87");}
    }
    
    
    
    
    /// Delete the booking 
    public void detele_booking(String booking_ind)
    {
        try{
            String sql = "DELETE FROM `bookings` WHERE `Ind_book` =?";
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1, booking_ind);
            boolean rs = ps.execute();
            if (rs)
            {
                System.out.println("done");
                setRoom_vacant(Booking_Index);
            }
            JOptionPane.showMessageDialog(null, "Deleted");
            this.dispose();
            
        }
        catch(SQLException e){ System.out.println("3"+e);}
    }
    
    
    
    /// set rooms to be vacant 
    public void setRoom_vacant(String booking_ind)
    {
        try{
           
            String sql = ("UPDATE `each_room` SET `room_occupancy`='Vacant',`booked_from`= null,`booked_to`= null,`Booked_by_firstname`='',`Booked_by_lastname`='' ,`Related_bookingIndex` =''    WHERE `Related_bookingIndex` ='"+booking_ind+"'");
            PreparedStatement ps = cn.prepareStatement(sql);
            int rs = ps.executeUpdate();
            if (rs>1){System.out.println("done");}
            
            
        }
        catch(SQLException e){ System.out.println(e);}
    }
    
    public Booking_delete_confirm() {
        initComponents();
        this.setLocationRelativeTo(null);
        update();
    }
    
    public String Booking_Index ="";
    public Booking_delete_confirm(String BookingIndex, Connection con) {
        initComponents();
        this.setLocationRelativeTo(null);
        cn = con;
        Booking_Index = BookingIndex;
        firstname_textbox.setText(BookingIndex);
        display_deatils(BookingIndex);
        update();
    }

    // update all the data
    public void update()
    {
        get_set_data pop = new get_set_data();
        pop.main(cn);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Booking_delete_main_panel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        deleteSelectedBooking_button = new javax.swing.JButton();
        firstName_lable = new javax.swing.JLabel();
        lastName_lable = new javax.swing.JLabel();
        dateFrom_label = new javax.swing.JLabel();
        dateTo_label = new javax.swing.JLabel();
        noFoAdults_label = new javax.swing.JLabel();
        noFoChildren_label = new javax.swing.JLabel();
        identificationNo_lable = new javax.swing.JLabel();
        firstname_textbox = new javax.swing.JTextField();
        lastname_textbox = new javax.swing.JTextField();
        dateFrom_textbox = new javax.swing.JTextField();
        dateTo_textbox = new javax.swing.JTextField();
        noAdult_textbox = new javax.swing.JTextField();
        noChildren_textbox = new javax.swing.JTextField();
        icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Booking_delete_main_panel.setBackground(new java.awt.Color(255, 255, 255));

        closeButton.setBackground(new java.awt.Color(0, 102, 255));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("X");
        closeButton.setToolTipText("");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        deleteSelectedBooking_button.setBackground(new java.awt.Color(204, 0, 0));
        deleteSelectedBooking_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteSelectedBooking_button.setForeground(new java.awt.Color(255, 255, 255));
        deleteSelectedBooking_button.setText("Delete");
        deleteSelectedBooking_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelectedBooking_buttonActionPerformed(evt);
            }
        });

        firstName_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firstName_lable.setForeground(new java.awt.Color(51, 102, 255));
        firstName_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstName_lable.setText(" First Name");

        lastName_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lastName_lable.setForeground(new java.awt.Color(51, 102, 255));
        lastName_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastName_lable.setText("Last Name");

        dateFrom_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dateFrom_label.setForeground(new java.awt.Color(51, 102, 255));
        dateFrom_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateFrom_label.setText("Date From");
        dateFrom_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateFrom_labelMouseClicked(evt);
            }
        });

        dateTo_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dateTo_label.setForeground(new java.awt.Color(51, 102, 255));
        dateTo_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateTo_label.setText("Date To ");
        dateTo_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateTo_labelMouseClicked(evt);
            }
        });

        noFoAdults_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        noFoAdults_label.setForeground(new java.awt.Color(51, 102, 255));
        noFoAdults_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        noFoAdults_label.setText("No.of Adults ");

        noFoChildren_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        noFoChildren_label.setForeground(new java.awt.Color(51, 102, 255));
        noFoChildren_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        noFoChildren_label.setText("No.of  Children");

        identificationNo_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        identificationNo_lable.setForeground(new java.awt.Color(51, 102, 255));
        identificationNo_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        identificationNo_lable.setText("Identification");

        firstname_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firstname_textbox.setForeground(new java.awt.Color(0, 102, 255));

        lastname_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lastname_textbox.setForeground(new java.awt.Color(0, 102, 255));

        dateFrom_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dateFrom_textbox.setForeground(new java.awt.Color(0, 102, 255));

        dateTo_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dateTo_textbox.setForeground(new java.awt.Color(0, 102, 255));

        noAdult_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        noAdult_textbox.setForeground(new java.awt.Color(0, 102, 255));

        noChildren_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        noChildren_textbox.setForeground(new java.awt.Color(0, 102, 255));

        icon.setPreferredSize(new java.awt.Dimension(359, 270));

        javax.swing.GroupLayout Booking_delete_main_panelLayout = new javax.swing.GroupLayout(Booking_delete_main_panel);
        Booking_delete_main_panel.setLayout(Booking_delete_main_panelLayout);
        Booking_delete_main_panelLayout.setHorizontalGroup(
            Booking_delete_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Booking_delete_main_panelLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(Booking_delete_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Booking_delete_main_panelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(firstname_textbox))
                    .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Booking_delete_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteSelectedBooking_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(Booking_delete_main_panelLayout.createSequentialGroup()
                .addGroup(Booking_delete_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(identificationNo_lable)
                    .addComponent(noFoAdults_label)
                    .addComponent(dateTo_label)
                    .addComponent(lastName_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstName_lable)
                    .addComponent(dateFrom_label)
                    .addComponent(noFoChildren_label))
                .addGap(18, 18, 18)
                .addGroup(Booking_delete_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noAdult_textbox)
                    .addComponent(dateFrom_textbox)
                    .addComponent(dateTo_textbox)
                    .addComponent(lastname_textbox)
                    .addComponent(noChildren_textbox))
                .addGap(218, 218, 218))
        );
        Booking_delete_main_panelLayout.setVerticalGroup(
            Booking_delete_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Booking_delete_main_panelLayout.createSequentialGroup()
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteSelectedBooking_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Booking_delete_main_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Booking_delete_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstname_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstName_lable))
                .addGroup(Booking_delete_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Booking_delete_main_panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lastName_lable)
                        .addGap(18, 18, 18)
                        .addGroup(Booking_delete_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateFrom_label)
                            .addComponent(dateFrom_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(Booking_delete_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateTo_label)
                            .addComponent(dateTo_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Booking_delete_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noFoAdults_label)
                            .addComponent(noAdult_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Booking_delete_main_panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastname_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Booking_delete_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Booking_delete_main_panelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(noFoChildren_label)
                        .addGap(26, 26, 26)
                        .addComponent(identificationNo_lable))
                    .addGroup(Booking_delete_main_panelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(noChildren_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Booking_delete_main_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Booking_delete_main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void deleteSelectedBooking_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedBooking_buttonActionPerformed
        // TODO add your handling code here:
        detele_booking(Booking_Index);
        


    }//GEN-LAST:event_deleteSelectedBooking_buttonActionPerformed

    private void dateFrom_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateFrom_labelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFrom_labelMouseClicked

    private void dateTo_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateTo_labelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTo_labelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking_delete_confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking_delete_confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking_delete_confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking_delete_confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking_delete_confirm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Booking_delete_main_panel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel dateFrom_label;
    private javax.swing.JTextField dateFrom_textbox;
    private javax.swing.JLabel dateTo_label;
    private javax.swing.JTextField dateTo_textbox;
    private javax.swing.JButton deleteSelectedBooking_button;
    private javax.swing.JLabel firstName_lable;
    private javax.swing.JTextField firstname_textbox;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel identificationNo_lable;
    private javax.swing.JLabel lastName_lable;
    private javax.swing.JTextField lastname_textbox;
    private javax.swing.JTextField noAdult_textbox;
    private javax.swing.JTextField noChildren_textbox;
    private javax.swing.JLabel noFoAdults_label;
    private javax.swing.JLabel noFoChildren_label;
    // End of variables declaration//GEN-END:variables
}
