/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loop;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Frank
 */
public class employeeDelete_confirmation extends javax.swing.JFrame {

     public Connection cn;
    public Statement st;
    
     /*public void conection() {

        try {
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loop_hotel?zeroDateTimeBehavior=convertToNull", "root", "");
            st = cn.createStatement();
            System.out.println("conected");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "not conected");
        }
    }*/
    
    
    public employeeDelete_confirmation() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public String empno;
    public String fullname;
    public employeeDelete_confirmation(String EmpNo, String Fullname, Connection con) {
        initComponents();
        cn = con;
        empno=EmpNo;
        this.setLocationRelativeTo(null);
        
        selectedEmployee_textbox.setText(EmpNo);
        selectedemployeename_textbox.setText(Fullname);
    }
    
    public void delete()
     {
         try{
            String sql = "DELETE FROM `login_employee` WHERE `Emp.no` ='"+empno+"'";
            PreparedStatement ps = cn.prepareStatement(sql);
            boolean rs = ps.execute();
            if (rs){System.out.println("done");}
        }
        catch(SQLException e){ System.out.println(e);}
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeButton2 = new javax.swing.JButton();
        selectedEmployee_textbox = new javax.swing.JTextField();
        roomNo_lable = new javax.swing.JLabel();
        delete_button = new javax.swing.JButton();
        roomNo_lable1 = new javax.swing.JLabel();
        selectedemployeename_textbox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        closeButton2.setBackground(new java.awt.Color(0, 102, 255));
        closeButton2.setForeground(new java.awt.Color(255, 255, 255));
        closeButton2.setText("X");
        closeButton2.setToolTipText("");
        closeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton2ActionPerformed(evt);
            }
        });

        selectedEmployee_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        selectedEmployee_textbox.setToolTipText("");
        selectedEmployee_textbox.setCaretColor(new java.awt.Color(255, 255, 255));
        selectedEmployee_textbox.setDisabledTextColor(new java.awt.Color(51, 102, 255));
        selectedEmployee_textbox.setEnabled(false);
        selectedEmployee_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedEmployee_textboxActionPerformed(evt);
            }
        });

        roomNo_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        roomNo_lable.setForeground(new java.awt.Color(51, 102, 255));
        roomNo_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roomNo_lable.setText("Emp No.");

        delete_button.setBackground(new java.awt.Color(255, 0, 0));
        delete_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delete_button.setForeground(new java.awt.Color(255, 255, 255));
        delete_button.setText("Delete");
        delete_button.setToolTipText("");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        roomNo_lable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        roomNo_lable1.setForeground(new java.awt.Color(51, 102, 255));
        roomNo_lable1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roomNo_lable1.setText("Name");

        selectedemployeename_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        selectedemployeename_textbox.setToolTipText("");
        selectedemployeename_textbox.setCaretColor(new java.awt.Color(255, 255, 255));
        selectedemployeename_textbox.setDisabledTextColor(new java.awt.Color(51, 102, 255));
        selectedemployeename_textbox.setEnabled(false);
        selectedemployeename_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedemployeename_textboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomNo_lable1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roomNo_lable, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectedemployeename_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectedEmployee_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(closeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedEmployee_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomNo_lable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomNo_lable1)
                    .addComponent(selectedemployeename_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButton2ActionPerformed

    private void selectedEmployee_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedEmployee_textboxActionPerformed

    }//GEN-LAST:event_selectedEmployee_textboxActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // TODO add your handling code here:
        delete();
        this.dispose();
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void selectedemployeename_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedemployeename_textboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedemployeename_textboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeDelete_confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeDelete_confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeDelete_confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeDelete_confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeeDelete_confirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton2;
    private javax.swing.JButton delete_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel roomNo_lable;
    private javax.swing.JLabel roomNo_lable1;
    private javax.swing.JTextField selectedEmployee_textbox;
    private javax.swing.JTextField selectedemployeename_textbox;
    // End of variables declaration//GEN-END:variables
}
