/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loop;

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;

/**
 *
 * @author Frank
 */
public class employee_edit extends javax.swing.JFrame {

     public Connection cn;
    public Statement st;
    //connection method
   /* public void conection() {

        try {
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loop_hotel?zeroDateTimeBehavior=convertToNull", "root", "");
            st = cn.createStatement();
            System.out.println("conected");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "not conected");
        }
    }*/
    
    public void Setdata(String empno)throws Exception
    {
        try{
                String sql = ("SELECT * FROM `login_employee` WHERE `Emp.no`= '"+empno+"'");
                PreparedStatement ps = cn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                while(rs.next())
                {
                    Date dateIn = rs.getDate("Date_of_birth");
                    
                    empNo_textbox.setText(rs.getString("Emp.no"));
                    firstName_textbox.setText(rs.getString("First_name"));
                    lastName_textbox.setText(rs.getString("Last_name"));
                    employeeDOB_datechooser.setDate(dateIn);
                    gender_combobox.setSelectedItem(rs.getString("Gender"));
                    authorityLevel_combobox.setSelectedItem(rs.getString("authority"));

                }
            }
            catch(SQLException e){ System.out.println(e);}
    }
    public void getdata(String empno)
    {
         try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String dob = "";
                
                dob = sdf.format(employeeDOB_datechooser.getDate());
                String Empno = empNo_textbox.getText();
                String first_name = firstName_textbox.getText();
                String last_name = lastName_textbox.getText();
                String gender = gender_combobox.getSelectedItem().toString();
                String authority = authorityLevel_combobox.getSelectedItem().toString();
                
                        
                        
                String sql = "UPDATE `login_employee` SET `Emp.no`='"+Empno+"',`authority`='"+authority+"',`First_name`='"+first_name+"',`Last_name`='"+last_name+"',`Gender`='"+gender+"',`Date_of_birth`='"+dob+"' WHERE `Emp.no` = '"+empno+"'";
                PreparedStatement ps = cn.prepareStatement(sql);
                int rs = ps.executeUpdate();
                if(rs > 0  ){JOptionPane.showMessageDialog(null, "submitted");}
                

                

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }
    
    
    public employee_edit() {
         initComponents();
        this.setLocationRelativeTo(null);
        
    }
    public String empno;
    public employee_edit(String Empno, Connection con) throws Exception {
        initComponents();
        cn = con;
        this.setLocationRelativeTo(null);
        Setdata(Empno);
        empno = Empno;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        firstName_lable = new javax.swing.JLabel();
        lastName_lable = new javax.swing.JLabel();
        firstName_lable1 = new javax.swing.JLabel();
        lastName_lable1 = new javax.swing.JLabel();
        lastName_lable2 = new javax.swing.JLabel();
        lastName_lable4 = new javax.swing.JLabel();
        hotel_lable = new javax.swing.JLabel();
        reservation_lable = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        empNo_textbox = new javax.swing.JTextField();
        firstName_textbox = new javax.swing.JTextField();
        lastName_textbox = new javax.swing.JTextField();
        gender_combobox = new javax.swing.JComboBox<>();
        authorityLevel_combobox = new javax.swing.JComboBox<>();
        addRemoveRoomType_button = new javax.swing.JButton();
        employeeDOB_datechooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        firstName_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firstName_lable.setForeground(new java.awt.Color(255, 255, 255));
        firstName_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstName_lable.setText(" First Name");

        lastName_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lastName_lable.setForeground(new java.awt.Color(255, 255, 255));
        lastName_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastName_lable.setText(" Last Name");

        firstName_lable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firstName_lable1.setForeground(new java.awt.Color(255, 255, 255));
        firstName_lable1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstName_lable1.setText(" Employee No.");

        lastName_lable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lastName_lable1.setForeground(new java.awt.Color(255, 255, 255));
        lastName_lable1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastName_lable1.setText("Gender");

        lastName_lable2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lastName_lable2.setForeground(new java.awt.Color(255, 255, 255));
        lastName_lable2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastName_lable2.setText("Authority");

        lastName_lable4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lastName_lable4.setForeground(new java.awt.Color(255, 255, 255));
        lastName_lable4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastName_lable4.setText("Date of Birth");

        hotel_lable.setBackground(new java.awt.Color(0, 204, 255));
        hotel_lable.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        hotel_lable.setForeground(new java.awt.Color(255, 255, 255));
        hotel_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotel_lable.setText("Management");
        hotel_lable.setToolTipText("");

        reservation_lable.setBackground(new java.awt.Color(0, 204, 255));
        reservation_lable.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        reservation_lable.setForeground(new java.awt.Color(255, 255, 255));
        reservation_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        reservation_lable.setText("Hotel ");
        reservation_lable.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstName_lable1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstName_lable, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastName_lable1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastName_lable2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(reservation_lable))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(hotel_lable)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lastName_lable)
                                .addGap(14, 14, 14))
                            .addComponent(lastName_lable4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(reservation_lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hotel_lable)
                .addGap(38, 38, 38)
                .addComponent(firstName_lable1)
                .addGap(31, 31, 31)
                .addComponent(firstName_lable)
                .addGap(40, 40, 40)
                .addComponent(lastName_lable)
                .addGap(41, 41, 41)
                .addComponent(lastName_lable1)
                .addGap(36, 36, 36)
                .addComponent(lastName_lable2)
                .addGap(52, 52, 52)
                .addComponent(lastName_lable4)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        closeButton.setBackground(new java.awt.Color(0, 102, 255));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("X");
        closeButton.setToolTipText("");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        empNo_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        empNo_textbox.setForeground(new java.awt.Color(51, 102, 255));
        empNo_textbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empNo_textboxMouseClicked(evt);
            }
        });
        empNo_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNo_textboxActionPerformed(evt);
            }
        });

        firstName_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firstName_textbox.setForeground(new java.awt.Color(51, 102, 255));
        firstName_textbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstName_textboxMouseClicked(evt);
            }
        });
        firstName_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName_textboxActionPerformed(evt);
            }
        });

        lastName_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lastName_textbox.setForeground(new java.awt.Color(51, 102, 255));
        lastName_textbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastName_textboxMouseClicked(evt);
            }
        });
        lastName_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastName_textboxActionPerformed(evt);
            }
        });

        gender_combobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gender_combobox.setForeground(new java.awt.Color(51, 102, 255));
        gender_combobox.setMaximumRowCount(300);
        gender_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        authorityLevel_combobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        authorityLevel_combobox.setForeground(new java.awt.Color(51, 102, 255));
        authorityLevel_combobox.setMaximumRowCount(300);
        authorityLevel_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Common_Access", "Admin_Access" }));

        addRemoveRoomType_button.setBackground(new java.awt.Color(51, 102, 255));
        addRemoveRoomType_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addRemoveRoomType_button.setForeground(new java.awt.Color(255, 255, 255));
        addRemoveRoomType_button.setText("Edit");
        addRemoveRoomType_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRemoveRoomType_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(empNo_textbox, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(firstName_textbox)
                            .addComponent(lastName_textbox)
                            .addComponent(employeeDOB_datechooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(addRemoveRoomType_button, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gender_combobox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authorityLevel_combobox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(empNo_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstName_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastName_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(gender_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(authorityLevel_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addRemoveRoomType_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDOB_datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void empNo_textboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empNo_textboxMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_empNo_textboxMouseClicked

    private void empNo_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNo_textboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNo_textboxActionPerformed

    private void firstName_textboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstName_textboxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName_textboxMouseClicked

    private void firstName_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName_textboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName_textboxActionPerformed

    private void lastName_textboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastName_textboxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lastName_textboxMouseClicked

    private void lastName_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastName_textboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastName_textboxActionPerformed

    private void addRemoveRoomType_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRemoveRoomType_buttonActionPerformed
        // TODO add your handling code here:
        getdata(empno);
        this.dispose();
    }//GEN-LAST:event_addRemoveRoomType_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee_edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRemoveRoomType_button;
    private javax.swing.JComboBox<String> authorityLevel_combobox;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField empNo_textbox;
    private com.toedter.calendar.JDateChooser employeeDOB_datechooser;
    private javax.swing.JLabel firstName_lable;
    private javax.swing.JLabel firstName_lable1;
    private javax.swing.JTextField firstName_textbox;
    private javax.swing.JComboBox<String> gender_combobox;
    private javax.swing.JLabel hotel_lable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastName_lable;
    private javax.swing.JLabel lastName_lable1;
    private javax.swing.JLabel lastName_lable2;
    private javax.swing.JLabel lastName_lable4;
    private javax.swing.JTextField lastName_textbox;
    private javax.swing.JLabel reservation_lable;
    // End of variables declaration//GEN-END:variables
}
