/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loop;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.*;



        
/**
 *
 * @author Frank
 */
public class login extends javax.swing.JFrame {

   
        public Connection cn;
        public Statement st;
        
   /* public void conection()    
    {    
        
       try
        {
             cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loop_hotel?zeroDateTimeBehavior=convertToNull", "root","");
             st = cn.createStatement();
             System.out.println("conected");
            
        }
        catch(SQLException e )
        {
            JOptionPane.showMessageDialog(null,"not conected" );
        }
    }*/
   
   
   public void update()
    {
        get_set_data pop = new get_set_data();
        pop.main(cn);
    }
            
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
       cn = connect.connects();
        update();
        
        
        
          
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forgot_frame = new javax.swing.JInternalFrame();
        jButton2 = new javax.swing.JButton();
        not_conected_frame = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        master_pane = new javax.swing.JPanel();
        style1_pane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        closeButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        error1 = new javax.swing.JLabel();
        forgotPassword_button = new javax.swing.JButton();
        pass_show = new javax.swing.JToggleButton();
        error2 = new javax.swing.JLabel();

        forgot_frame.setVisible(true);

        jButton2.setText("jButton2");

        javax.swing.GroupLayout forgot_frameLayout = new javax.swing.GroupLayout(forgot_frame.getContentPane());
        forgot_frame.getContentPane().setLayout(forgot_frameLayout);
        forgot_frameLayout.setHorizontalGroup(
            forgot_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forgot_frameLayout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(131, 131, 131))
        );
        forgot_frameLayout.setVerticalGroup(
            forgot_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forgot_frameLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(139, 139, 139))
        );

        not_conected_frame.setVisible(true);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("not conected");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout not_conected_frameLayout = new javax.swing.GroupLayout(not_conected_frame.getContentPane());
        not_conected_frame.getContentPane().setLayout(not_conected_frameLayout);
        not_conected_frameLayout.setHorizontalGroup(
            not_conected_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, not_conected_frameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(not_conected_frameLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        not_conected_frameLayout.setVerticalGroup(
            not_conected_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(not_conected_frameLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setResizable(false);

        master_pane.setBackground(new java.awt.Color(255, 255, 255));

        style1_pane.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Reservation");
        jLabel1.setToolTipText("");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Source Code Pro Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Username");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Source Code Pro Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password");

        jLabel4.setBackground(new java.awt.Color(0, 204, 255));
        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Hotel ");
        jLabel4.setToolTipText("");

        javax.swing.GroupLayout style1_paneLayout = new javax.swing.GroupLayout(style1_pane);
        style1_pane.setLayout(style1_paneLayout);
        style1_paneLayout.setHorizontalGroup(
            style1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(style1_paneLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(style1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, style1_paneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(style1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        style1_paneLayout.setVerticalGroup(
            style1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(style1_paneLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        UsernameTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        UsernameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameTextFieldMouseClicked(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        closeButton.setBackground(new java.awt.Color(0, 102, 255));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("X");
        closeButton.setToolTipText("");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(0, 102, 255));
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginButtonKeyPressed(evt);
            }
        });

        error1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        error1.setForeground(new java.awt.Color(204, 0, 0));

        forgotPassword_button.setBackground(new java.awt.Color(0, 102, 255));
        forgotPassword_button.setForeground(new java.awt.Color(255, 255, 255));
        forgotPassword_button.setText("Forget Password");
        forgotPassword_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPassword_buttonActionPerformed(evt);
            }
        });
        forgotPassword_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                forgotPassword_buttonKeyPressed(evt);
            }
        });

        pass_show.setBackground(new java.awt.Color(255, 255, 255));
        pass_show.setForeground(new java.awt.Color(0, 102, 255));
        pass_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-closed-eye-64.png"))); // NOI18N
        pass_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_showActionPerformed(evt);
            }
        });

        error2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        error2.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout master_paneLayout = new javax.swing.GroupLayout(master_pane);
        master_pane.setLayout(master_paneLayout);
        master_paneLayout.setHorizontalGroup(
            master_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(master_paneLayout.createSequentialGroup()
                .addComponent(style1_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(master_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(master_paneLayout.createSequentialGroup()
                        .addGroup(master_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(master_paneLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UsernameTextField)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, master_paneLayout.createSequentialGroup()
                                .addComponent(forgotPassword_button, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, master_paneLayout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addComponent(pass_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(106, 106, 106))
                    .addGroup(master_paneLayout.createSequentialGroup()
                        .addComponent(error2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(master_paneLayout.createSequentialGroup()
                        .addComponent(error1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        master_paneLayout.setVerticalGroup(
            master_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(style1_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(master_paneLayout.createSequentialGroup()
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(error1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(error2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(master_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pass_show, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(master_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(forgotPassword_button, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(master_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(master_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
       String username = UsernameTextField.getText();
       String password = jPasswordField1.getText();
        boolean userpass = false;
        boolean passpass = false;
        // check blank 
        if(username.equals("")){error1.setText("*");}
        if(password.equals("")){error2.setText("*");}
       // Check username 
       try{ 
            String sql = "SELECT * FROM `login_employee` WHERE `username` = '"+username+"'";
            System.out.println(1);
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()){userpass=true;System.out.println(userpass);}
            else{error1.setText("invalid username");}
          }catch(SQLException e){ System.out.println(e);}
        try{ 
            String sql = "SELECT * FROM `login_employee` WHERE `password` = '"+password+"' AND `username` = '"+username+"'";
             System.out.println(2);
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()){passpass=true; System.out.println(passpass);}
            else {error2.setText("invalid password");}
          }catch(SQLException e){ System.out.println(e);}
       
        //Username is right and password is right 
        if (userpass==true && passpass==true)
        { try{
            String sql = "SELECT * FROM `login_employee` WHERE `username` = '"+username+"'  AND `password` ='"+ password+"'";
             System.out.println(3);
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {    
                String passuser = rs.getString("username"); 
                String pass_word=rs.getString("password");
                
              if(passuser.equals(username) && pass_word.equals(password))
              {
                 new mainMenu(passuser, cn).setVisible(true);
                 this.dispose();
              }
              else{error1.setText("invalid username");error2.setText("invalid username");}
            }
        }catch(SQLException e){ System.out.println(e);}
    }  
    }//GEN-LAST:event_loginButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void UsernameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameTextFieldMouseClicked
        // TODO add your handling code here:
        error1.setText("");
    }//GEN-LAST:event_UsernameTextFieldMouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        // TODO add your handling code here:
        error2.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void loginButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginButtonKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_loginButtonKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void forgotPassword_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPassword_buttonActionPerformed
        // TODO add your handling code here:
        new forgot_passwordORusername(cn).setVisible(true);
    }//GEN-LAST:event_forgotPassword_buttonActionPerformed

    private void forgotPassword_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_forgotPassword_buttonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_forgotPassword_buttonKeyPressed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void pass_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_showActionPerformed
        // TODO add your handling code here:
        System.out.println(pass_show.isSelected());
        if(pass_show.isSelected())
        {
            jPasswordField1.setEchoChar((char)0);
            //Image m =  Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon8-eye-unchecked-64.png"));
            ImageIcon imageicon = new ImageIcon("icons8-eye-unchecked-64.png");
            pass_show.setIcon(imageicon);
        }
        else
        {
             jPasswordField1.setEchoChar('*');
             ImageIcon imageicon = new ImageIcon("icons8-closed-eye-64.png");
            pass_show.setIcon(imageicon);
        }
    }//GEN-LAST:event_pass_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JButton forgotPassword_button;
    private javax.swing.JInternalFrame forgot_frame;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel master_pane;
    private javax.swing.JInternalFrame not_conected_frame;
    private javax.swing.JToggleButton pass_show;
    private javax.swing.JPanel style1_pane;
    // End of variables declaration//GEN-END:variables
}
