/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loop;
import java.sql.*;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Yash
 */
public class print_records extends javax.swing.JFrame {

    // variables
    private String _username;
    public Connection cn;
    public Statement st;
    public int x ;
    public int y;
    static int xx,yy;
    private boolean size = true;
    private String selectedBookingIndex= "";
    private String Searchby ="";
    private String SearchBy="";
    
    //connection method
    /*public void conection() {

        try {
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loop_hotel?zeroDateTimeBehavior=convertToNull", "root", "");
            st = cn.createStatement();
            System.out.println("conected");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "not conected");
        }
    }*/
    
    
    public print_records() {
        initComponents();
        this.setLocationRelativeTo(null);
        bookingLog_pane.setVisible(true);
        accountManagement_pane.setVisible(false);
         for_all.doClick();
         searchAll.doClick();
    }
    public print_records(String username, Connection con) {
        initComponents();
        this.setLocationRelativeTo(null);
        bookingLog_pane.setVisible(true);
        accountManagement_pane.setVisible(false);
         for_all.doClick();
         searchAll.doClick();
         cn = con;
         _username= username;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Main_panel = new javax.swing.JPanel();
        style1_pane = new javax.swing.JPanel();
        hotel_lable = new javax.swing.JLabel();
        reservation_lable = new javax.swing.JLabel();
        avaliablity_button = new javax.swing.JButton();
        booking_button = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        closeButton2 = new javax.swing.JButton();
        closeButton1 = new javax.swing.JButton();
        closeButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        bookingLog_pane = new javax.swing.JPanel();
        firstName_lable3 = new javax.swing.JLabel();
        searchName_textbox = new javax.swing.JTextField();
        print_Booking_button = new javax.swing.JButton();
        search_firstname = new javax.swing.JRadioButton();
        datechooser_Search = new com.toedter.calendar.JDateChooser();
        search_lastname = new javax.swing.JRadioButton();
        search_date = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingLog_table = new javax.swing.JTable();
        search_button = new javax.swing.JButton();
        firstName_lable1 = new javax.swing.JLabel();
        resettBookingTable_button = new javax.swing.JButton();
        firstName_lable2 = new javax.swing.JLabel();
        selectedRoom_textBox = new javax.swing.JTextField();
        for_all = new javax.swing.JRadioButton();
        accountManagement_pane = new javax.swing.JPanel();
        serachEmployee_lable = new javax.swing.JLabel();
        serachBox_textfield = new javax.swing.JTextField();
        searchByName_radio = new javax.swing.JRadioButton();
        searchByEmpNo_radio = new javax.swing.JRadioButton();
        search_button1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        employeeTable_table = new javax.swing.JTable();
        resetEmployeeTable_button = new javax.swing.JButton();
        selectedEmployee_textfield = new javax.swing.JTextField();
        serachEmployee_lable1 = new javax.swing.JLabel();
        printEmployeeRecords_button = new javax.swing.JButton();
        searchAll = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Main_panel.setBackground(new java.awt.Color(255, 255, 255));

        style1_pane.setBackground(new java.awt.Color(51, 102, 255));

        hotel_lable.setBackground(new java.awt.Color(0, 204, 255));
        hotel_lable.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        hotel_lable.setForeground(new java.awt.Color(255, 255, 255));
        hotel_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotel_lable.setText("Records");
        hotel_lable.setToolTipText("");

        reservation_lable.setBackground(new java.awt.Color(0, 204, 255));
        reservation_lable.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        reservation_lable.setForeground(new java.awt.Color(255, 255, 255));
        reservation_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        reservation_lable.setText("Print");
        reservation_lable.setToolTipText("");

        avaliablity_button.setBackground(new java.awt.Color(255, 255, 255));
        avaliablity_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        avaliablity_button.setForeground(new java.awt.Color(51, 102, 255));
        avaliablity_button.setText("Booking R.");
        avaliablity_button.setToolTipText("");
        avaliablity_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliablity_buttonActionPerformed(evt);
            }
        });

        booking_button.setBackground(new java.awt.Color(255, 255, 255));
        booking_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        booking_button.setForeground(new java.awt.Color(51, 102, 255));
        booking_button.setText("Employee R.");
        booking_button.setToolTipText("");
        booking_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booking_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout style1_paneLayout = new javax.swing.GroupLayout(style1_pane);
        style1_pane.setLayout(style1_paneLayout);
        style1_paneLayout.setHorizontalGroup(
            style1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(style1_paneLayout.createSequentialGroup()
                .addComponent(hotel_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(style1_paneLayout.createSequentialGroup()
                .addGroup(style1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(style1_paneLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(style1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(booking_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avaliablity_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(style1_paneLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(reservation_lable)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        style1_paneLayout.setVerticalGroup(
            style1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(style1_paneLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(reservation_lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hotel_lable)
                .addGap(56, 56, 56)
                .addComponent(avaliablity_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(booking_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(423, Short.MAX_VALUE))
        );

        closeButton.setBackground(new java.awt.Color(0, 102, 255));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("X");
        closeButton.setToolTipText("");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        closeButton2.setBackground(new java.awt.Color(0, 102, 255));
        closeButton2.setForeground(new java.awt.Color(255, 255, 255));
        closeButton2.setText("=");
        closeButton2.setToolTipText("");
        closeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton2ActionPerformed(evt);
            }
        });

        closeButton1.setBackground(new java.awt.Color(0, 102, 255));
        closeButton1.setForeground(new java.awt.Color(255, 255, 255));
        closeButton1.setText("-");
        closeButton1.setToolTipText("");
        closeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton1ActionPerformed(evt);
            }
        });

        closeButton3.setBackground(new java.awt.Color(0, 102, 255));
        closeButton3.setForeground(new java.awt.Color(255, 255, 255));
        closeButton3.setText("<");
        closeButton3.setToolTipText("");
        closeButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton3ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });

        bookingLog_pane.setBackground(new java.awt.Color(255, 255, 255));
        bookingLog_pane.setForeground(new java.awt.Color(255, 255, 255));

        firstName_lable3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firstName_lable3.setForeground(new java.awt.Color(51, 102, 255));
        firstName_lable3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstName_lable3.setText(" Name");

        searchName_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchName_textbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchName_textboxMouseClicked(evt);
            }
        });
        searchName_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchName_textboxActionPerformed(evt);
            }
        });

        print_Booking_button.setBackground(new java.awt.Color(51, 102, 255));
        print_Booking_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        print_Booking_button.setForeground(new java.awt.Color(255, 255, 255));
        print_Booking_button.setText("Print/Save");
        print_Booking_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_Booking_buttonActionPerformed(evt);
            }
        });

        buttonGroup2.add(search_firstname);
        search_firstname.setText("Search By First name");
        search_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_firstnameActionPerformed(evt);
            }
        });

        datechooser_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datechooser_SearchMouseClicked(evt);
            }
        });

        buttonGroup2.add(search_lastname);
        search_lastname.setText("Search By last name");
        search_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_lastnameActionPerformed(evt);
            }
        });

        buttonGroup2.add(search_date);
        search_date.setText("Search By Date ");
        search_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_dateActionPerformed(evt);
            }
        });

        bookingLog_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index No.", "First Name", "last Name", "Booked From", "Booked To", "Booked Rooms", "Total Cost ", "No. Children", "No. Adults "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bookingLog_table.setRowHeight(20);
        bookingLog_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingLog_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookingLog_table);

        search_button.setBackground(new java.awt.Color(51, 102, 255));
        search_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        search_button.setForeground(new java.awt.Color(255, 255, 255));
        search_button.setText("Search");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        firstName_lable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firstName_lable1.setForeground(new java.awt.Color(51, 102, 255));
        firstName_lable1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstName_lable1.setText("Date ");

        resettBookingTable_button.setBackground(new java.awt.Color(51, 102, 255));
        resettBookingTable_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        resettBookingTable_button.setForeground(new java.awt.Color(255, 255, 255));
        resettBookingTable_button.setText("Reset");
        resettBookingTable_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resettBookingTable_buttonActionPerformed(evt);
            }
        });

        firstName_lable2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firstName_lable2.setForeground(new java.awt.Color(51, 102, 255));
        firstName_lable2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstName_lable2.setText("Ind No.");

        selectedRoom_textBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        selectedRoom_textBox.setDisabledTextColor(new java.awt.Color(51, 102, 255));
        selectedRoom_textBox.setEnabled(false);
        selectedRoom_textBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectedRoom_textBoxMouseClicked(evt);
            }
        });
        selectedRoom_textBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedRoom_textBoxActionPerformed(evt);
            }
        });

        buttonGroup2.add(for_all);
        for_all.setText("Search For All");
        for_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_allActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookingLog_paneLayout = new javax.swing.GroupLayout(bookingLog_pane);
        bookingLog_pane.setLayout(bookingLog_paneLayout);
        bookingLog_paneLayout.setHorizontalGroup(
            bookingLog_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingLog_paneLayout.createSequentialGroup()
                .addGroup(bookingLog_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingLog_paneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(firstName_lable2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectedRoom_textBox)
                        .addGap(40, 40, 40)
                        .addComponent(resettBookingTable_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(print_Booking_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bookingLog_paneLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(bookingLog_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstName_lable3)
                            .addComponent(firstName_lable1))
                        .addGap(18, 18, 18)
                        .addGroup(bookingLog_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datechooser_Search, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(searchName_textbox))
                        .addGap(32, 32, 32)
                        .addGroup(bookingLog_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search_firstname)
                            .addComponent(search_date)
                            .addComponent(search_lastname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(bookingLog_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(for_all)))
                    .addGroup(bookingLog_paneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        bookingLog_paneLayout.setVerticalGroup(
            bookingLog_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingLog_paneLayout.createSequentialGroup()
                .addGroup(bookingLog_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingLog_paneLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(bookingLog_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchName_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstName_lable3))
                        .addGap(18, 18, 18)
                        .addGroup(bookingLog_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datechooser_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingLog_paneLayout.createSequentialGroup()
                                .addComponent(firstName_lable1)
                                .addGap(9, 9, 9))))
                    .addGroup(bookingLog_paneLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(search_firstname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_lastname)
                        .addGap(20, 20, 20)
                        .addComponent(search_date))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingLog_paneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(for_all)
                        .addGap(18, 18, 18)
                        .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(bookingLog_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(print_Booking_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resettBookingTable_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstName_lable2)
                    .addComponent(selectedRoom_textBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        accountManagement_pane.setBackground(new java.awt.Color(255, 255, 255));
        accountManagement_pane.setPreferredSize(new java.awt.Dimension(796, 621));

        serachEmployee_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        serachEmployee_lable.setForeground(new java.awt.Color(51, 102, 255));
        serachEmployee_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        serachEmployee_lable.setText("Search Employee");

        serachBox_textfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        serachBox_textfield.setForeground(new java.awt.Color(51, 102, 255));

        searchByName_radio.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(searchByName_radio);
        searchByName_radio.setForeground(new java.awt.Color(51, 102, 255));
        searchByName_radio.setText("Search By Last Name");
        searchByName_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByName_radioActionPerformed(evt);
            }
        });

        searchByEmpNo_radio.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(searchByEmpNo_radio);
        searchByEmpNo_radio.setForeground(new java.awt.Color(51, 102, 255));
        searchByEmpNo_radio.setSelected(true);
        searchByEmpNo_radio.setText("Search By Employee No.");
        searchByEmpNo_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByEmpNo_radioActionPerformed(evt);
            }
        });

        search_button1.setBackground(new java.awt.Color(51, 102, 255));
        search_button1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        search_button1.setForeground(new java.awt.Color(255, 255, 255));
        search_button1.setText("Search");
        search_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_button1ActionPerformed(evt);
            }
        });

        employeeTable_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee No.", "First Name", "Last Name", "Gender", "Date of Birth", "Authority"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        employeeTable_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeTable_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(employeeTable_table);

        resetEmployeeTable_button.setBackground(new java.awt.Color(51, 102, 255));
        resetEmployeeTable_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        resetEmployeeTable_button.setForeground(new java.awt.Color(255, 255, 255));
        resetEmployeeTable_button.setText("Reset Table");
        resetEmployeeTable_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetEmployeeTable_buttonActionPerformed(evt);
            }
        });

        selectedEmployee_textfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        selectedEmployee_textfield.setForeground(new java.awt.Color(51, 102, 255));
        selectedEmployee_textfield.setEnabled(false);
        selectedEmployee_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedEmployee_textfieldActionPerformed(evt);
            }
        });

        serachEmployee_lable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        serachEmployee_lable1.setForeground(new java.awt.Color(51, 102, 255));
        serachEmployee_lable1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        serachEmployee_lable1.setText("Selected Employee");

        printEmployeeRecords_button.setBackground(new java.awt.Color(51, 102, 255));
        printEmployeeRecords_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        printEmployeeRecords_button.setForeground(new java.awt.Color(255, 255, 255));
        printEmployeeRecords_button.setText("Print/Save");
        printEmployeeRecords_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printEmployeeRecords_buttonActionPerformed(evt);
            }
        });

        searchAll.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(searchAll);
        searchAll.setForeground(new java.awt.Color(51, 102, 255));
        searchAll.setText("Search All");
        searchAll.setToolTipText("");
        searchAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountManagement_paneLayout = new javax.swing.GroupLayout(accountManagement_pane);
        accountManagement_pane.setLayout(accountManagement_paneLayout);
        accountManagement_paneLayout.setHorizontalGroup(
            accountManagement_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountManagement_paneLayout.createSequentialGroup()
                .addGroup(accountManagement_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountManagement_paneLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(accountManagement_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resetEmployeeTable_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serachEmployee_lable1))
                        .addGap(18, 18, 18)
                        .addGroup(accountManagement_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(printEmployeeRecords_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectedEmployee_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(accountManagement_paneLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(serachEmployee_lable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serachBox_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(accountManagement_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchByEmpNo_radio)
                            .addComponent(searchByName_radio)
                            .addComponent(searchAll))
                        .addGap(18, 18, 18)
                        .addComponent(search_button1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        accountManagement_paneLayout.setVerticalGroup(
            accountManagement_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountManagement_paneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(accountManagement_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountManagement_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(serachEmployee_lable)
                        .addComponent(serachBox_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(search_button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountManagement_paneLayout.createSequentialGroup()
                        .addComponent(searchAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchByName_radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchByEmpNo_radio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(accountManagement_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serachEmployee_lable1)
                    .addComponent(selectedEmployee_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(accountManagement_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printEmployeeRecords_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetEmployeeTable_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLayeredPane1.setLayer(bookingLog_pane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(accountManagement_pane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bookingLog_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(accountManagement_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bookingLog_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(accountManagement_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout Main_panelLayout = new javax.swing.GroupLayout(Main_panel);
        Main_panel.setLayout(Main_panelLayout);
        Main_panelLayout.setHorizontalGroup(
            Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_panelLayout.createSequentialGroup()
                .addComponent(style1_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Main_panelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(closeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(closeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane1)))
        );
        Main_panelLayout.setVerticalGroup(
            Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(style1_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Main_panelLayout.createSequentialGroup()
                .addGroup(Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(closeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(closeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(closeButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avaliablity_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliablity_buttonActionPerformed
        // TODO add your handling code here:
        bookingLog_pane.setVisible(true);
        accountManagement_pane.setVisible(false);
         for_all.doClick();
        
    }//GEN-LAST:event_avaliablity_buttonActionPerformed

    private void booking_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booking_buttonActionPerformed
        // TODO add your handling code here:
        bookingLog_pane.setVisible(false);
        accountManagement_pane.setVisible(true);
        searchAll.doClick();
    }//GEN-LAST:event_booking_buttonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void closeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton1ActionPerformed
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_closeButton1ActionPerformed

    private void closeButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton3ActionPerformed
        // TODO add your handling code here:

        new admin_options(_username, cn).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeButton3ActionPerformed

    private void closeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton2ActionPerformed
        // TODO add your handling code here:

        // xtxfhxcrxytjcjrxjxcty
        if(size)
        {
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            int x =this.getHeight();
            int e = this.getWidth();
            System.out.println(e+" "+x);
            size = false;
        }
        else
        {
            this.setSize(997, 678);
            this.setLocationRelativeTo(null);
            size = true;
        }
    }//GEN-LAST:event_closeButton2ActionPerformed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-yy);

    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed

        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel1MouseReleased

    private void searchName_textboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchName_textboxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchName_textboxMouseClicked

    private void searchName_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchName_textboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchName_textboxActionPerformed

    private void print_Booking_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_Booking_buttonActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Booking Records");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try
        {
            System.out.println("d");
            PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
            System.out.println("d");
            set.add(OrientationRequested.LANDSCAPE);
            System.out.println("d");
            bookingLog_table.print(JTable.PrintMode.FIT_WIDTH,header,footer,true,set,false);
            System.out.println("d");
        
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("Cannot print %s&n",e.getMessage());
        }

    }//GEN-LAST:event_print_Booking_buttonActionPerformed

    private void search_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_firstnameActionPerformed
        // TODO add your handling code here:
        Searchby = "FirstName";
    }//GEN-LAST:event_search_firstnameActionPerformed

    private void datechooser_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datechooser_SearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_datechooser_SearchMouseClicked

    private void search_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_lastnameActionPerformed
        // TODO add your handling code here:
        Searchby = "LastName";
    }//GEN-LAST:event_search_lastnameActionPerformed

    private void search_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_dateActionPerformed
        // TODO add your handling code here:
        Searchby = "Date";
    }//GEN-LAST:event_search_dateActionPerformed

    private void bookingLog_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingLog_tableMouseClicked
        // TODO add your handling code here:

        //get the selected row
        DefaultTableModel model = (DefaultTableModel)bookingLog_table.getModel();
        int select = bookingLog_table.getSelectedRow();
        selectedBookingIndex =model.getValueAt(select,0).toString();
        selectedRoom_textBox.setText(selectedBookingIndex);

    }//GEN-LAST:event_bookingLog_tableMouseClicked

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
        //get all the records
        if (Searchby.equals(""))
        {
            DefaultTableModel model = (DefaultTableModel)bookingLog_table.getModel();
            while(model.getRowCount() > 0)
            {
                model.removeRow(0);
            }
            try{
                String sql = ("SELECT * FROM `bookings` ");
                PreparedStatement ps = cn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                while(rs.next())
                {

                    String firstname = rs.getString("Booked_by_firstname");
                    String lastname = rs.getString("Booked_by_lastname");
                    String bookedFrom = rs.getString("Booked_from");
                    String bookedTo = rs.getString("Booked_to");
                    String bookedRooms = rs.getString("Booked_rooms");
                    String totcost = rs.getString("Total_cost");
                    String num_children = rs.getString("No. of Children");
                    String num_adult = rs.getString("No. of Adults");
                    String bookingInd = String.valueOf(rs.getInt("Ind_book"));
                    model.addRow(new Object [] {bookingInd ,firstname,lastname,bookedFrom,bookedTo,bookedRooms,totcost,num_children,num_adult});

                }
            }
            catch(SQLException e){ System.out.println(e);}
        }

        // get records by firstname
        if (Searchby.equals("FirstName"))
        {
            DefaultTableModel model = (DefaultTableModel)bookingLog_table.getModel();
            while(model.getRowCount() > 0)
            {
                model.removeRow(0);
            }
            String name = searchName_textbox.getText();
            try{
                String sql = ("SELECT * FROM `bookings` WHERE `Booked_by_firstname` ='"+name+"'");
                PreparedStatement ps = cn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                while(rs.next())
                {

                    String firstname = rs.getString("Booked_by_firstname");
                    String lastname = rs.getString("Booked_by_lastname");
                    String bookedFrom = rs.getString("Booked_from");
                    String bookedTo = rs.getString("Booked_to");
                    String bookedRooms = rs.getString("Booked_rooms");
                    String totcost = rs.getString("Total_cost");
                    String num_children = rs.getString("No. of Children");
                    String num_adult = rs.getString("No. of Adults");
                    model.addRow(new Object [] {firstname,lastname,bookedFrom,bookedTo,bookedRooms,totcost,num_children,num_adult});

                }
            }
            catch(SQLException e){ System.out.println(e);}
        }

        // get records by lasttname
        if (Searchby.equals("LastName"))
        {
            DefaultTableModel model = (DefaultTableModel)bookingLog_table.getModel();
            while(model.getRowCount() > 0)
            {
                model.removeRow(0);
            }
            String name = searchName_textbox.getText();
            try{
                String sql = ("SELECT * FROM `bookings` WHERE `Booked_by_lastname` ='"+name+"'");
                PreparedStatement ps = cn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                while(rs.next())
                {

                    String firstname = rs.getString("Booked_by_firstname");
                    String lastname = rs.getString("Booked_by_lastname");
                    String bookedFrom = rs.getString("Booked_from");
                    String bookedTo = rs.getString("Booked_to");
                    String bookedRooms = rs.getString("Booked_rooms");
                    String totcost = rs.getString("Total_cost");
                    String num_children = rs.getString("No. of Children");
                    String num_adult = rs.getString("No. of Adults");
                    model.addRow(new Object [] {firstname,lastname,bookedFrom,bookedTo,bookedRooms,totcost,num_children,num_adult});

                }
            }
            catch(SQLException e){ System.out.println(e);}
        }

        // get records by Date
        if (Searchby.equals("Date"))
        {
            DefaultTableModel model = (DefaultTableModel)bookingLog_table.getModel();
            while(model.getRowCount() > 0)
            {
                model.removeRow(0);
            }
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

            String date = sdf.format(datechooser_Search.getDate());
            try{
                String sql = ("SELECT * FROM `bookings` WHERE `Booked_from` <='"+date+"'  AND '"+date+"'<=`Booked_to`");
                PreparedStatement ps = cn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                while(rs.next())
                {

                    String firstname = rs.getString("Booked_by_firstname");
                    String lastname = rs.getString("Booked_by_lastname");
                    String bookedFrom = rs.getString("Booked_from");
                    String bookedTo = rs.getString("Booked_to");
                    String bookedRooms = rs.getString("Booked_rooms");
                    String totcost = rs.getString("Total_cost");
                    String num_children = rs.getString("No. of Children");
                    String num_adult = rs.getString("No. of Adults");
                    model.addRow(new Object [] {firstname,lastname,bookedFrom,bookedTo,bookedRooms,totcost,num_children,num_adult});

                }
            }
            catch(SQLException e){ System.out.println(e);}
        }
    }//GEN-LAST:event_search_buttonActionPerformed

    private void resettBookingTable_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resettBookingTable_buttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)bookingLog_table.getModel();
        {
            model.removeRow(0);
        }

    }//GEN-LAST:event_resettBookingTable_buttonActionPerformed

    private void selectedRoom_textBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectedRoom_textBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedRoom_textBoxMouseClicked

    private void selectedRoom_textBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedRoom_textBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedRoom_textBoxActionPerformed

    private void for_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_allActionPerformed
        // TODO add your handling code here:
        Searchby = "";
    }//GEN-LAST:event_for_allActionPerformed

    private void searchByName_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByName_radioActionPerformed
        // TODO add your handling code here:
        SearchBy = "searchBylastName";
    }//GEN-LAST:event_searchByName_radioActionPerformed

    private void searchByEmpNo_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByEmpNo_radioActionPerformed
        // TODO add your handling code here:
        SearchBy = "searchByEmployeeNo";
    }//GEN-LAST:event_searchByEmpNo_radioActionPerformed

    private void search_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_button1ActionPerformed
        // TODO add your handling code here:
        if(SearchBy.equals("searchBylastName"))
        {
            String searchby = serachBox_textfield.getText();
            employeeTable_table.setModel(new DefaultTableModel(null, new String[] {"Employee No.","First Name","Last Name","Gender","Date Of Birth","Authority"}));
            DefaultTableModel model = (DefaultTableModel)employeeTable_table.getModel();
            try{
                String sql = ("SELECT * FROM `login_employee` WHERE `Last_name` = '"+searchby+"'");
                PreparedStatement ps = cn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                while(rs.next())
                {

                    String EmployeeNo = rs.getString("Emp.no");
                    String firstName = rs.getString("First_name");
                    String lastName = rs.getString("Last_name");
                    String gender = rs.getString("Gender");
                    String dateOfBirth = rs.getString("Date_of_birth");
                    String authority = rs.getString("authority");
                    model.addRow(new Object [] {EmployeeNo,firstName,lastName,gender,dateOfBirth,authority});

                }
            }
            catch(SQLException e){ System.out.println(e);}
        }
        if(SearchBy.equals("searchByEmployeeNo"))
        {
            String searchby = serachBox_textfield.getText();
            employeeTable_table.setModel(new DefaultTableModel(null, new String[] {"Employee No.","First Name","Last Name","Gender","Date Of Birth","Authority"}));
            DefaultTableModel model = (DefaultTableModel)employeeTable_table.getModel();
            try{
                String sql = ("SELECT * FROM `login_employee` WHERE `Emp.no` = '"+searchby+"'");
                PreparedStatement ps = cn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                while(rs.next())
                {

                    String EmployeeNo = rs.getString("Emp.no");
                    String firstName = rs.getString("First_name");
                    String lastName = rs.getString("Last_name");
                    String gender = rs.getString("Gender");
                    String dateOfBirth = rs.getString("Date_of_birth");
                    String authority = rs.getString("authority");
                    model.addRow(new Object [] {EmployeeNo,firstName,lastName,gender,dateOfBirth,authority});

                }
            }
            catch(SQLException e){ System.out.println(e);}
        }
        if(SearchBy.equals(""))
        {

            employeeTable_table.setModel(new DefaultTableModel(null, new String[] {"Employee No.","First Name","Last Name","Gender","Date Of Birth","Authority"}));
            DefaultTableModel model = (DefaultTableModel)employeeTable_table.getModel();
            try{
                String sql = ("SELECT * FROM `login_employee` ");
                PreparedStatement ps = cn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                while(rs.next())
                {

                    String EmployeeNo = rs.getString("Emp.no");
                    String firstName = rs.getString("First_name");
                    String lastName = rs.getString("Last_name");
                    String gender = rs.getString("Gender");
                    String dateOfBirth = rs.getString("Date_of_birth");
                    String authority = rs.getString("authority");
                    model.addRow(new Object [] {EmployeeNo,firstName,lastName,gender,dateOfBirth,authority});

                }
            }
            catch(SQLException e){ System.out.println(e);}
        }
    }//GEN-LAST:event_search_button1ActionPerformed

    private void employeeTable_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeTable_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)employeeTable_table.getModel();
        int select = employeeTable_table.getSelectedRow();
        String selectedEmp =model.getValueAt(select,0).toString();
        selectedEmployee_textfield.setText(selectedEmp);
        String Firstname = model.getValueAt(select, 1).toString();
        String Lastname = model.getValueAt(select,2).toString();;
        String fullname = Firstname+" "+Lastname;
        System.out.println(fullname);
        System.out.println(selectedEmp);
    }//GEN-LAST:event_employeeTable_tableMouseClicked

    private void resetEmployeeTable_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetEmployeeTable_buttonActionPerformed
        // TODO add your handling code here:efwg
        
        DefaultTableModel model = (DefaultTableModel)employeeTable_table.getModel();
         while(model.getRowCount() > 0)
        {
            model.removeRow(0);
        }
    }//GEN-LAST:event_resetEmployeeTable_buttonActionPerformed

    private void selectedEmployee_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedEmployee_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedEmployee_textfieldActionPerformed

    private void printEmployeeRecords_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printEmployeeRecords_buttonActionPerformed
        // TODO add your handling code here:
        
        MessageFormat header = new MessageFormat("Booking Records");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try
        {
            PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
            set.add(OrientationRequested.LANDSCAPE);
            employeeTable_table.print(JTable.PrintMode.FIT_WIDTH,header,footer,true,set,false);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("Cannot print %s&n",e.getMessage());
        }
        
    }//GEN-LAST:event_printEmployeeRecords_buttonActionPerformed

    private void searchAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAllActionPerformed
        // TODO add your handling code here:

        SearchBy = "";
    }//GEN-LAST:event_searchAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new print_records().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main_panel;
    private javax.swing.JPanel accountManagement_pane;
    private javax.swing.JButton avaliablity_button;
    private javax.swing.JPanel bookingLog_pane;
    private javax.swing.JTable bookingLog_table;
    private javax.swing.JButton booking_button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton closeButton1;
    private javax.swing.JButton closeButton2;
    private javax.swing.JButton closeButton3;
    private com.toedter.calendar.JDateChooser datechooser_Search;
    private javax.swing.JTable employeeTable_table;
    private javax.swing.JLabel firstName_lable1;
    private javax.swing.JLabel firstName_lable2;
    private javax.swing.JLabel firstName_lable3;
    private javax.swing.JRadioButton for_all;
    private javax.swing.JLabel hotel_lable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton printEmployeeRecords_button;
    private javax.swing.JButton print_Booking_button;
    private javax.swing.JLabel reservation_lable;
    private javax.swing.JButton resetEmployeeTable_button;
    private javax.swing.JButton resettBookingTable_button;
    private javax.swing.JRadioButton searchAll;
    private javax.swing.JRadioButton searchByEmpNo_radio;
    private javax.swing.JRadioButton searchByName_radio;
    private javax.swing.JTextField searchName_textbox;
    private javax.swing.JButton search_button;
    private javax.swing.JButton search_button1;
    private javax.swing.JRadioButton search_date;
    private javax.swing.JRadioButton search_firstname;
    private javax.swing.JRadioButton search_lastname;
    private javax.swing.JTextField selectedEmployee_textfield;
    private javax.swing.JTextField selectedRoom_textBox;
    private javax.swing.JTextField serachBox_textfield;
    private javax.swing.JLabel serachEmployee_lable;
    private javax.swing.JLabel serachEmployee_lable1;
    private javax.swing.JPanel style1_pane;
    // End of variables declaration//GEN-END:variables
}
