/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loop;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Frank
 */
public class putRoom_inOutService extends javax.swing.JFrame {

    public Connection cn = null;
    public Statement st = null;
    
   /* public void conection() {

        try {
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loop_hotel?zeroDateTimeBehavior=convertToNull", "root", "");
            st = cn.createStatement();
            System.out.println("conected");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "not conected");
        }
    }
    */
    public void Table_set( )
    {
        
        Service_table.setModel(new DefaultTableModel(null, new String[] {"Room No.","Status"}));
        DefaultTableModel model = (DefaultTableModel)Service_table.getModel();
        String selected_item = String.valueOf(RoomType_combobox.getSelectedItem());
        try
        {
            String sql = "SELECT `room_no`, `room_in_out_service` FROM `each_room` WHERE `room_type` ='"+selected_item+"'";
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {
                String room_no = rs.getString("room_no");
                String room_status = rs.getString("room_in_out_service");
                model.addRow(new Object [] {room_no,room_status});
            }
        }
        
        catch(SQLException e){ System.out.println(e);}
        
        }
    
    
    public void RoomType_combobox()
    {
         try{
            String sql = "SELECT `Room_type` FROM `rooms`  ";
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {
                RoomType_combobox.addItem(rs.getString("Room_type"));
                
            }
        }
        catch(SQLException e){ System.out.println(e);}
    }
    public putRoom_inOutService() {
        initComponents();
        RoomType_combobox();
        this.setLocationRelativeTo(null);
        Table_set();
    }
    public putRoom_inOutService(Connection con) {
        initComponents();
        cn = con;
        RoomType_combobox();
        this.setLocationRelativeTo(null);
        Table_set();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        style_pane = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        RoomType_combobox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Service_table = new javax.swing.JTable();
        roomType_combobox = new javax.swing.JComboBox<>();
        selectedRoom_textbox = new javax.swing.JTextField();
        set_button = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        roomNo_lable1 = new javax.swing.JLabel();
        roomNo_lable2 = new javax.swing.JLabel();
        roomNo_lable = new javax.swing.JLabel();
        roomNo_lable3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        style_pane.setBackground(new java.awt.Color(255, 255, 255));

        closeButton.setBackground(new java.awt.Color(0, 102, 255));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("X");
        closeButton.setToolTipText("");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        RoomType_combobox.setBackground(new java.awt.Color(51, 102, 255));
        RoomType_combobox.setForeground(new java.awt.Color(255, 255, 255));
        RoomType_combobox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomType_comboboxMouseClicked(evt);
            }
        });
        RoomType_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomType_comboboxActionPerformed(evt);
            }
        });

        Service_table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Service_table.setForeground(new java.awt.Color(51, 102, 255));
        Service_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No.", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Service_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Service_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Service_table);

        roomType_combobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomType_combobox.setForeground(new java.awt.Color(51, 102, 255));
        roomType_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Service", "Out of Service" }));

        selectedRoom_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        selectedRoom_textbox.setToolTipText("");
        selectedRoom_textbox.setCaretColor(new java.awt.Color(255, 255, 255));
        selectedRoom_textbox.setDisabledTextColor(new java.awt.Color(51, 102, 255));
        selectedRoom_textbox.setEnabled(false);
        selectedRoom_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedRoom_textboxActionPerformed(evt);
            }
        });

        set_button.setBackground(new java.awt.Color(0, 102, 255));
        set_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        set_button.setForeground(new java.awt.Color(255, 255, 255));
        set_button.setText("Set");
        set_button.setToolTipText("");
        set_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_buttonActionPerformed(evt);
            }
        });

        search_button.setBackground(new java.awt.Color(0, 102, 255));
        search_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        search_button.setForeground(new java.awt.Color(255, 255, 255));
        search_button.setText("Search");
        search_button.setToolTipText("");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        roomNo_lable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        roomNo_lable1.setForeground(new java.awt.Color(255, 255, 255));
        roomNo_lable1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roomNo_lable1.setText("Room Type");

        roomNo_lable2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        roomNo_lable2.setForeground(new java.awt.Color(255, 255, 255));
        roomNo_lable2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roomNo_lable2.setText("Status");

        roomNo_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        roomNo_lable.setForeground(new java.awt.Color(255, 255, 255));
        roomNo_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roomNo_lable.setText("Room No.");

        roomNo_lable3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        roomNo_lable3.setForeground(new java.awt.Color(255, 255, 255));
        roomNo_lable3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roomNo_lable3.setText("Room Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(roomNo_lable))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomNo_lable2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomNo_lable1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roomNo_lable3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roomNo_lable3)
                .addGap(63, 63, 63)
                .addComponent(roomNo_lable1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roomNo_lable)
                .addGap(52, 52, 52)
                .addComponent(roomNo_lable2)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout style_paneLayout = new javax.swing.GroupLayout(style_pane);
        style_pane.setLayout(style_paneLayout);
        style_paneLayout.setHorizontalGroup(
            style_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(style_paneLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(style_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(style_paneLayout.createSequentialGroup()
                        .addGroup(style_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(style_paneLayout.createSequentialGroup()
                                .addComponent(RoomType_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(style_paneLayout.createSequentialGroup()
                                .addGroup(style_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectedRoom_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roomType_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)
                                .addComponent(set_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, style_paneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        style_paneLayout.setVerticalGroup(
            style_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(style_paneLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(style_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RoomType_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(selectedRoom_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(roomType_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, style_paneLayout.createSequentialGroup()
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(set_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(style_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(style_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void RoomType_comboboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomType_comboboxMouseClicked

    }//GEN-LAST:event_RoomType_comboboxMouseClicked

    private void RoomType_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomType_comboboxActionPerformed

    }//GEN-LAST:event_RoomType_comboboxActionPerformed

    private void set_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_buttonActionPerformed
        // TODO add your handling code here:
      try {
                String iop = roomType_combobox.getSelectedItem().toString();
                DefaultTableModel model = (DefaultTableModel)Service_table.getModel();
                int select = Service_table.getSelectedRow();
                String room_no = model.getValueAt(select,0).toString();
                selectedRoom_textbox.setText(room_no);
                
                String sql = "UPDATE `each_room` SET `room_in_out_service`='"+iop+"' WHERE `room_no` = '"+room_no+"'";
                PreparedStatement ps = cn.prepareStatement(sql);
                int rs = ps.executeUpdate();
                
                if (rs>0){
                Table_set();
                }
                

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_set_buttonActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
        
      Table_set();
    }//GEN-LAST:event_search_buttonActionPerformed

    private void selectedRoom_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedRoom_textboxActionPerformed
      
    }//GEN-LAST:event_selectedRoom_textboxActionPerformed

    private void Service_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Service_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Service_table.getModel();
        int select = Service_table.getSelectedRow();
        selectedRoom_textbox.setText(model.getValueAt(select,0).toString());
        System.out.println(model.getValueAt(select, 0).toString());
    }//GEN-LAST:event_Service_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(putRoom_inOutService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(putRoom_inOutService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(putRoom_inOutService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(putRoom_inOutService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new putRoom_inOutService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> RoomType_combobox;
    private javax.swing.JTable Service_table;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel roomNo_lable;
    private javax.swing.JLabel roomNo_lable1;
    private javax.swing.JLabel roomNo_lable2;
    private javax.swing.JLabel roomNo_lable3;
    private javax.swing.JComboBox<String> roomType_combobox;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField selectedRoom_textbox;
    private javax.swing.JButton set_button;
    private javax.swing.JPanel style_pane;
    // End of variables declaration//GEN-END:variables
}
