/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loop;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Frank
 */
public class roomAdditionRemoval extends javax.swing.JFrame {
    
    
    public Connection cn;
    public Statement st;
    
     /*public void conection() {

        try {
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loop_hotel?zeroDateTimeBehavior=convertToNull", "root", "");
            st = cn.createStatement();
            System.out.println("conected");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "not conected");
        }
    }
    */
      public void RoomType_combobox()
    {
         try{
            String sql = "SELECT `Room_type` FROM `rooms`  ";
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {
                roomType_combobox.addItem(rs.getString("Room_type"));
                roomtype_combobox.addItem(rs.getString("Room_type"));
            }
        }
        catch(SQLException e){ System.out.println(e);}
    }
    
      public void Table_set( )
    {
        
        roomTable.setModel(new DefaultTableModel(null, new String[] {"Room No.","Room Type","Occupancy"}));
        DefaultTableModel model = (DefaultTableModel)roomTable.getModel();
        String selected_item = roomtype_combobox.getSelectedItem().toString();
        try
        {
            String sql = "SELECT `room_no`, `room_type`, `room_occupancy` FROM `each_room` WHERE `room_type` = '"+selected_item+"'";
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {
                String room_no = rs.getString("room_no");
                String room_type = rs.getString("room_type");
                String room_occupancy = rs.getString("room_occupancy");
                model.addRow(new Object [] {room_no,room_type,room_occupancy});
            }
        }
        
        
        
        catch(SQLException e){ System.out.println(e);}
        
        }
      public void Table_allset( )
    {
        
        roomTable.setModel(new DefaultTableModel(null, new String[] {"Room No.","Room Type","Occupancy"}));
        DefaultTableModel model = (DefaultTableModel)roomTable.getModel();
        
        try
        {
            String sql = "SELECT `room_no`, `room_type`, `room_occupancy` FROM `each_room` ";
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {
                String room_no = rs.getString("room_no");
                String room_type = rs.getString("room_type");
                String room_occupancy = rs.getString("room_occupancy");
                model.addRow(new Object [] {room_no,room_type,room_occupancy});
            }
        }
        
        
        
        catch(SQLException e){ System.out.println(e);}
        
        }
      
      
      
      
      
    
    public roomAdditionRemoval() {
        initComponents();
        RoomType_combobox();
        this.setLocationRelativeTo(null);
        addroom_pane.setVisible(true);
        removeRoom_pane.setVisible(false);
        
    }
     public roomAdditionRemoval(Connection con) {
        initComponents();
        cn = con;
        RoomType_combobox();
        this.setLocationRelativeTo(null);
        addroom_pane.setVisible(true);
        removeRoom_pane.setVisible(false);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        style1_pane = new javax.swing.JPanel();
        style2_pane = new javax.swing.JPanel();
        hotel_lable = new javax.swing.JLabel();
        reModeling_lable = new javax.swing.JLabel();
        removeRoom_button = new javax.swing.JButton();
        addRoom_button = new javax.swing.JButton();
        closeButton2 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        addroom_pane = new javax.swing.JPanel();
        roomnno_lable = new javax.swing.JLabel();
        roomno_textbox = new javax.swing.JTextField();
        roomtype_lable = new javax.swing.JLabel();
        roomType_combobox = new javax.swing.JComboBox<>();
        addroom_button = new javax.swing.JButton();
        removeRoom_pane = new javax.swing.JPanel();
        roomtype_lable_ = new javax.swing.JLabel();
        roomtype_combobox = new javax.swing.JComboBox<>();
        search_button = new javax.swing.JButton();
        roomscroll = new javax.swing.JScrollPane();
        roomTable = new javax.swing.JTable();
        delete_button = new javax.swing.JButton();
        allSearch_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        style1_pane.setBackground(new java.awt.Color(255, 255, 255));

        style2_pane.setBackground(new java.awt.Color(51, 102, 255));

        hotel_lable.setBackground(new java.awt.Color(0, 204, 255));
        hotel_lable.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        hotel_lable.setForeground(new java.awt.Color(255, 255, 255));
        hotel_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hotel_lable.setText("ReModeling");
        hotel_lable.setToolTipText("");

        reModeling_lable.setBackground(new java.awt.Color(0, 204, 255));
        reModeling_lable.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        reModeling_lable.setForeground(new java.awt.Color(255, 255, 255));
        reModeling_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        reModeling_lable.setText("Hotel ");
        reModeling_lable.setToolTipText("");

        removeRoom_button.setBackground(new java.awt.Color(255, 255, 255));
        removeRoom_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        removeRoom_button.setForeground(new java.awt.Color(51, 102, 255));
        removeRoom_button.setText("Remove Room");
        removeRoom_button.setToolTipText("");
        removeRoom_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRoom_buttonActionPerformed(evt);
            }
        });

        addRoom_button.setBackground(new java.awt.Color(255, 255, 255));
        addRoom_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addRoom_button.setForeground(new java.awt.Color(51, 102, 255));
        addRoom_button.setText("Add Room");
        addRoom_button.setToolTipText("");
        addRoom_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoom_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout style2_paneLayout = new javax.swing.GroupLayout(style2_pane);
        style2_pane.setLayout(style2_paneLayout);
        style2_paneLayout.setHorizontalGroup(
            style2_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(style2_paneLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(style2_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hotel_lable, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reModeling_lable, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(style2_paneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(style2_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addRoom_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeRoom_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        style2_paneLayout.setVerticalGroup(
            style2_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(style2_paneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(reModeling_lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hotel_lable)
                .addGap(59, 59, 59)
                .addComponent(addRoom_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(removeRoom_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        closeButton2.setBackground(new java.awt.Color(0, 102, 255));
        closeButton2.setForeground(new java.awt.Color(255, 255, 255));
        closeButton2.setText("X");
        closeButton2.setToolTipText("");
        closeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton2ActionPerformed(evt);
            }
        });

        addroom_pane.setBackground(new java.awt.Color(255, 255, 255));

        roomnno_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        roomnno_lable.setForeground(new java.awt.Color(51, 102, 255));
        roomnno_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roomnno_lable.setText("Room No.");

        roomno_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        roomno_textbox.setToolTipText("");
        roomno_textbox.setCaretColor(new java.awt.Color(255, 255, 255));
        roomno_textbox.setDisabledTextColor(new java.awt.Color(51, 102, 255));
        roomno_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomno_textboxActionPerformed(evt);
            }
        });

        roomtype_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        roomtype_lable.setForeground(new java.awt.Color(51, 102, 255));
        roomtype_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roomtype_lable.setText("Room Type");

        roomType_combobox.setBackground(new java.awt.Color(51, 102, 255));
        roomType_combobox.setForeground(new java.awt.Color(255, 255, 255));
        roomType_combobox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomType_comboboxMouseClicked(evt);
            }
        });
        roomType_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomType_comboboxActionPerformed(evt);
            }
        });

        addroom_button.setBackground(new java.awt.Color(0, 102, 255));
        addroom_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addroom_button.setForeground(new java.awt.Color(255, 255, 255));
        addroom_button.setText("Add");
        addroom_button.setToolTipText("");
        addroom_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addroom_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addroom_paneLayout = new javax.swing.GroupLayout(addroom_pane);
        addroom_pane.setLayout(addroom_paneLayout);
        addroom_paneLayout.setHorizontalGroup(
            addroom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addroom_paneLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(addroom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addroom_paneLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(roomnno_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomno_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addroom_paneLayout.createSequentialGroup()
                        .addComponent(roomtype_lable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addroom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addroom_button, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomType_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        addroom_paneLayout.setVerticalGroup(
            addroom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addroom_paneLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addGroup(addroom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomno_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomnno_lable))
                .addGap(18, 18, 18)
                .addGroup(addroom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomtype_lable)
                    .addComponent(roomType_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(addroom_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );

        removeRoom_pane.setBackground(new java.awt.Color(255, 255, 255));
        removeRoom_pane.setPreferredSize(new java.awt.Dimension(570, 594));

        roomtype_lable_.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        roomtype_lable_.setForeground(new java.awt.Color(51, 102, 255));
        roomtype_lable_.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roomtype_lable_.setText("Room Type");

        roomtype_combobox.setBackground(new java.awt.Color(51, 102, 255));
        roomtype_combobox.setForeground(new java.awt.Color(255, 255, 255));
        roomtype_combobox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomtype_comboboxMouseClicked(evt);
            }
        });
        roomtype_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomtype_comboboxActionPerformed(evt);
            }
        });

        search_button.setBackground(new java.awt.Color(0, 102, 255));
        search_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        search_button.setForeground(new java.awt.Color(255, 255, 255));
        search_button.setText("Search");
        search_button.setToolTipText("");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        roomTable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        roomTable.setForeground(new java.awt.Color(51, 102, 255));
        roomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No.", "Room Type", "Occupancy"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        roomTable.setRowHeight(30);
        roomTable.setRowMargin(2);
        roomTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomTableMouseClicked(evt);
            }
        });
        roomscroll.setViewportView(roomTable);

        delete_button.setBackground(new java.awt.Color(255, 0, 0));
        delete_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delete_button.setForeground(new java.awt.Color(255, 255, 255));
        delete_button.setText("Delete");
        delete_button.setToolTipText("");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        allSearch_button.setBackground(new java.awt.Color(0, 102, 255));
        allSearch_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        allSearch_button.setForeground(new java.awt.Color(255, 255, 255));
        allSearch_button.setText("Show All");
        allSearch_button.setToolTipText("");
        allSearch_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allSearch_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeRoom_paneLayout = new javax.swing.GroupLayout(removeRoom_pane);
        removeRoom_pane.setLayout(removeRoom_paneLayout);
        removeRoom_paneLayout.setHorizontalGroup(
            removeRoom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeRoom_paneLayout.createSequentialGroup()
                .addGroup(removeRoom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeRoom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(removeRoom_paneLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(roomtype_lable_)
                            .addGap(18, 18, 18)
                            .addComponent(roomtype_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(removeRoom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(removeRoom_paneLayout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(removeRoom_paneLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(roomscroll, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(removeRoom_paneLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(allSearch_button, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        removeRoom_paneLayout.setVerticalGroup(
            removeRoom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeRoom_paneLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(allSearch_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(removeRoom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeRoom_paneLayout.createSequentialGroup()
                        .addGroup(removeRoom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(removeRoom_paneLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(roomtype_lable_)))
                        .addGap(28, 28, 28)
                        .addComponent(roomscroll, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(roomtype_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(addroom_pane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(removeRoom_pane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addroom_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(removeRoom_pane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addroom_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(removeRoom_pane, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout style1_paneLayout = new javax.swing.GroupLayout(style1_pane);
        style1_pane.setLayout(style1_paneLayout);
        style1_paneLayout.setHorizontalGroup(
            style1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(style1_paneLayout.createSequentialGroup()
                .addComponent(style2_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(style1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(style1_paneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane1)))
        );
        style1_paneLayout.setVerticalGroup(
            style1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(style2_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(style1_paneLayout.createSequentialGroup()
                .addComponent(closeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(style1_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(style1_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButton2ActionPerformed

    private void removeRoom_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRoom_buttonActionPerformed
        // TODO add your handling code here:
       addroom_pane.setVisible(false);
        removeRoom_pane.setVisible(true);
       
    }//GEN-LAST:event_removeRoom_buttonActionPerformed

    private void addRoom_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoom_buttonActionPerformed
        // TODO add your handling code here:
        addroom_pane.setVisible(true);
        removeRoom_pane.setVisible(false);
    }//GEN-LAST:event_addRoom_buttonActionPerformed

    private void roomno_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomno_textboxActionPerformed

    }//GEN-LAST:event_roomno_textboxActionPerformed

    private void roomType_comboboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomType_comboboxMouseClicked

    }//GEN-LAST:event_roomType_comboboxMouseClicked

    private void roomType_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomType_comboboxActionPerformed

    }//GEN-LAST:event_roomType_comboboxActionPerformed

    private void addroom_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addroom_buttonActionPerformed
        // TODO add your handling code here:
         try {
                String roomNo = roomno_textbox.getText();
                String roomType = roomType_combobox.getSelectedItem().toString();
                String sql = "INSERT INTO `each_room`(`room_no`, `room_type`) VALUES ('"+roomNo+"','"+roomType+"')";
                PreparedStatement ps = cn.prepareStatement(sql);
                int rs = ps.executeUpdate();
                if(rs > 0  ){JOptionPane.showMessageDialog(null, "submitted");}
                roomno_textbox.setText("");

                

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        
    }//GEN-LAST:event_addroom_buttonActionPerformed

    private void roomtype_comboboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomtype_comboboxMouseClicked

    }//GEN-LAST:event_roomtype_comboboxMouseClicked

    private void roomtype_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomtype_comboboxActionPerformed

    }//GEN-LAST:event_roomtype_comboboxActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed

        Table_set();
    }//GEN-LAST:event_search_buttonActionPerformed

    private void roomTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomTableMouseClicked

        DefaultTableModel model = (DefaultTableModel)roomTable.getModel();
        int select = roomTable.getSelectedRow();
        String selectedRoom =model.getValueAt(select,0).toString();
    }//GEN-LAST:event_roomTableMouseClicked

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)roomTable.getModel();
        int select = roomTable.getSelectedRow();
        String selectedRoom =model.getValueAt(select,0).toString();
        new roomDeleteConfirmation(selectedRoom, cn).setVisible(true);
        roomTable.setModel(new DefaultTableModel(null, new String[] {"Room No.","Room Type","Occupancy"}));
        
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void allSearch_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allSearch_buttonActionPerformed
        // TODO add your handling code here:
        Table_allset();
    }//GEN-LAST:event_allSearch_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(roomAdditionRemoval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(roomAdditionRemoval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(roomAdditionRemoval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(roomAdditionRemoval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new roomAdditionRemoval().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoom_button;
    private javax.swing.JButton addroom_button;
    private javax.swing.JPanel addroom_pane;
    private javax.swing.JButton allSearch_button;
    private javax.swing.JButton closeButton2;
    private javax.swing.JButton delete_button;
    private javax.swing.JLabel hotel_lable;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel reModeling_lable;
    private javax.swing.JButton removeRoom_button;
    private javax.swing.JPanel removeRoom_pane;
    private javax.swing.JTable roomTable;
    private javax.swing.JComboBox<String> roomType_combobox;
    private javax.swing.JLabel roomnno_lable;
    private javax.swing.JTextField roomno_textbox;
    private javax.swing.JScrollPane roomscroll;
    private javax.swing.JComboBox<String> roomtype_combobox;
    private javax.swing.JLabel roomtype_lable;
    private javax.swing.JLabel roomtype_lable_;
    private javax.swing.JButton search_button;
    private javax.swing.JPanel style1_pane;
    private javax.swing.JPanel style2_pane;
    // End of variables declaration//GEN-END:variables
}
