/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Frank
 */
public class Security_questions extends javax.swing.JFrame {

    
     //connection variables
    public Connection cn;
    public Statement st;
    //connection method
   /* public void conection() {

        try {
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loop_hotel?zeroDateTimeBehavior=convertToNull", "root", "");
            st = cn.createStatement();
            System.out.println("conected");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "not conected");
        }
    }*/
    
    // input into the database 
    public void dataInput(String first_name, String last_name, String username, String password, String authority_level,
            String gender, String empNo, String dob,String passwordRe,String question,String Ans)
    {
         try {  //preparing the statement
                String sql = "INSERT INTO `login_employee`(`Emp.no`, `username`, `password`, `authority`, `First_name`, `Last_name`, `Gender`, `Date_of_birth`, `Security_Question` "
                        + ",`Security _Answer`) VALUES ('"+empNo+"','"+username+"','"+password+"','"+authority_level+"','"+first_name+"','"+last_name+"','"
                        +gender+"','"+dob+"','"+question+"','"+Ans+"')";
                PreparedStatement ps = cn.prepareStatement(sql);
                //execution of the update
                int rs = ps.executeUpdate();
                
                System.out.println("2");
                
                if(rs > 0  ){JOptionPane.showMessageDialog(null, "submitted");}
                this.dispose();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "There was an error. Please try again.");
            }
    }
    
    
    
    
    
    
    public Security_questions() {
        initComponents();
        this.setLocationRelativeTo(null);
        Error1.setVisible(false);
        Error2.setVisible(false);
    }

    // public variables 
    public String First_name = "";
    public String Last_name = "";
    public String Username = "";
    public String Password = "";
    public String Authority_level = "";
    public String Gender = "";
    public String EmpNo = "";
    public String Dob = "";
    public String PasswordRe = "";
    
    public Security_questions(String first_name, String last_name, String username, String password, String authority_level, String gender, String empNo, String dob,String passwordRe , Connection con) {
        initComponents();
        cn = con;
        this.setLocationRelativeTo(null);
        System.out.println("1");
        First_name =first_name ;
        Last_name = last_name;
        Username = username;
        Password = password;
        Authority_level = authority_level;
        Gender = gender;
        EmpNo = empNo;
        Dob = dob;
        PasswordRe = passwordRe;
        
        Error1.setVisible(false);
        Error2.setVisible(false);
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        serachEmployee_lable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Question = new javax.swing.JTextArea();
        serachEmployee_lable1 = new javax.swing.JLabel();
        Answer = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        Error1 = new javax.swing.JLabel();
        Error2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        closeButton.setBackground(new java.awt.Color(0, 102, 255));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("X");
        closeButton.setToolTipText("");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        serachEmployee_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        serachEmployee_lable.setForeground(new java.awt.Color(51, 102, 255));
        serachEmployee_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        serachEmployee_lable.setText("Security Question");

        Question.setColumns(20);
        Question.setForeground(new java.awt.Color(51, 102, 255));
        Question.setRows(5);
        Question.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuestionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Question);

        serachEmployee_lable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        serachEmployee_lable1.setForeground(new java.awt.Color(51, 102, 255));
        serachEmployee_lable1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        serachEmployee_lable1.setText("Answer");

        Answer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Answer.setForeground(new java.awt.Color(51, 102, 255));
        Answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerActionPerformed(evt);
            }
        });

        search_button.setBackground(new java.awt.Color(51, 102, 255));
        search_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        search_button.setForeground(new java.awt.Color(255, 255, 255));
        search_button.setText("Submit");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        Error1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Error1.setForeground(new java.awt.Color(255, 0, 0));
        Error1.setText("*");
        Error1.setToolTipText("");

        Error2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Error2.setForeground(new java.awt.Color(255, 0, 0));
        Error2.setText("*");
        Error2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addComponent(Answer)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serachEmployee_lable)
                            .addComponent(serachEmployee_lable1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Error1)
                    .addComponent(Error2))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serachEmployee_lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Error1))
                .addGap(18, 18, 18)
                .addComponent(serachEmployee_lable1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Error2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // get data from textboxes
        String question = Question.getText();
        String Ans = Answer.getText();
        // check data
        boolean c1  = question.equals("");
        boolean c2  = Ans.equals("");
        // Display error
        if(c1){Error1.setVisible(true);}
        if(c2){Error2.setVisible(true);}
        //
        if (c1 == false && c2 == false )
        {
            
            dataInput(First_name ,Last_name ,Username,Password ,Authority_level ,Gender ,  EmpNo,  Dob ,PasswordRe ,question,Ans);
            System.out.println("3");
        }
        
    }//GEN-LAST:event_search_buttonActionPerformed

    private void QuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuestionMouseClicked
        // TODO add your handling code here:
        Error1.setVisible(false);
    }//GEN-LAST:event_QuestionMouseClicked

    private void AnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerActionPerformed
        // TODO add your handling code here:
        Error2.setVisible(false);
    }//GEN-LAST:event_AnswerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Security_questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Security_questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Security_questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Security_questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Security_questions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Answer;
    private javax.swing.JLabel Error1;
    private javax.swing.JLabel Error2;
    private javax.swing.JTextArea Question;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search_button;
    private javax.swing.JLabel serachEmployee_lable;
    private javax.swing.JLabel serachEmployee_lable1;
    // End of variables declaration//GEN-END:variables
}
