/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loop;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*;
import javax.swing.*;



/**
 *
 * @author Frank
 */
public class side_workstation extends javax.swing.JFrame {
    public Connection cn;
    public Statement st;
    String filename = null;
    int s = 0 ;
    byte[] image_indentification= null;
    
     public void conection() {

        try {
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loop_hotel?zeroDateTimeBehavior=convertToNull", "root", "");
            st = cn.createStatement();
            System.out.println("conected");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "not conected");
        }
    }
     

    /**
     * Creates new form side_workstation
     */
    public side_workstation() {
        initComponents();
        conection();
        
        
        
    }
public String SearchBy = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Search_by = new javax.swing.ButtonGroup();
        Set_Password = new javax.swing.JPanel();
        passre_lable = new javax.swing.JLabel();
        answer_textbox = new javax.swing.JTextField();
        next1_button = new javax.swing.JButton();
        password_lable = new javax.swing.JLabel();
        answer_textbox1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Set_Password.setBackground(new java.awt.Color(255, 255, 255));

        passre_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passre_lable.setForeground(new java.awt.Color(51, 102, 255));
        passre_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passre_lable.setText("re-enter password");

        answer_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        answer_textbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answer_textboxMouseClicked(evt);
            }
        });
        answer_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_textboxActionPerformed(evt);
            }
        });

        next1_button.setBackground(new java.awt.Color(51, 102, 255));
        next1_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        next1_button.setForeground(new java.awt.Color(255, 255, 255));
        next1_button.setText("Submit");
        next1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1_buttonActionPerformed(evt);
            }
        });

        password_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        password_lable.setForeground(new java.awt.Color(51, 102, 255));
        password_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        password_lable.setText("new password");

        answer_textbox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        answer_textbox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answer_textbox1MouseClicked(evt);
            }
        });
        answer_textbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_textbox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Set_PasswordLayout = new javax.swing.GroupLayout(Set_Password);
        Set_Password.setLayout(Set_PasswordLayout);
        Set_PasswordLayout.setHorizontalGroup(
            Set_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Set_PasswordLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(next1_button, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Set_PasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Set_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passre_lable)
                    .addComponent(password_lable))
                .addGap(28, 28, 28)
                .addGroup(Set_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer_textbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answer_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Set_PasswordLayout.setVerticalGroup(
            Set_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Set_PasswordLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(Set_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer_textbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_lable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(Set_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passre_lable))
                .addGap(54, 54, 54)
                .addComponent(next1_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(Set_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(497, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(Set_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void next1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1_buttonActionPerformed
       
    }//GEN-LAST:event_next1_buttonActionPerformed

    private void answer_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_textboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_textboxActionPerformed

    private void answer_textboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answer_textboxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_textboxMouseClicked

    private void answer_textbox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answer_textbox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_textbox1MouseClicked

    private void answer_textbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_textbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_textbox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(side_workstation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(side_workstation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(side_workstation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(side_workstation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new side_workstation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Search_by;
    private javax.swing.JPanel Set_Password;
    private javax.swing.JTextField answer_textbox;
    private javax.swing.JTextField answer_textbox1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton next1_button;
    private javax.swing.JLabel passre_lable;
    private javax.swing.JLabel password_lable;
    private javax.swing.JPanel username_check;
    private javax.swing.JPanel username_check1;
    private javax.swing.JPanel username_check2;
    // End of variables declaration//GEN-END:variables
}
