/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loop;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Frank
 */
public class username_forgot extends javax.swing.JFrame {

     public String empno ="";
    
    public Connection cn = null;
    public Statement st;
        
   /* public void conection()    
    {    
        
       try
        {
             cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/loop_hotel?zeroDateTimeBehavior=convertToNull", "root","");
             st = cn.createStatement();
             System.out.println("conected");
            
        }
        catch(SQLException e )
        {
            JOptionPane.showMessageDialog(null,"not conected" );
        }
    }
    */
    
    permission c1 = new permission();
    public username_forgot() {
        initComponents();
        this.setLocationRelativeTo(null);
        empno_get_question.setVisible(true);
        question_ans.setVisible(false);
        Set_Password.setVisible(false);
    }
     public username_forgot(Connection con) {
        initComponents();
        cn = con;
        this.setLocationRelativeTo(null);
        empno_get_question.setVisible(true);
        question_ans.setVisible(false);
        Set_Password.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masterpane = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        masterpaneLayer = new javax.swing.JLayeredPane();
        empno_get_question = new javax.swing.JPanel();
        Lable = new javax.swing.JLabel();
        empno_textbox = new javax.swing.JTextField();
        next1_button = new javax.swing.JButton();
        question_ans = new javax.swing.JPanel();
        Answer_lable2 = new javax.swing.JLabel();
        answer_textbox2 = new javax.swing.JTextField();
        next1_button3 = new javax.swing.JButton();
        question_lable2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        question_textarea2 = new javax.swing.JTextArea();
        Set_Password = new javax.swing.JPanel();
        passre_lable = new javax.swing.JLabel();
        reenter_textbox = new javax.swing.JTextField();
        next1_button4 = new javax.swing.JButton();
        username_lable = new javax.swing.JLabel();
        username_textbox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        masterpane.setBackground(new java.awt.Color(255, 255, 255));

        closeButton.setBackground(new java.awt.Color(0, 102, 255));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("X");
        closeButton.setToolTipText("");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        empno_get_question.setBackground(new java.awt.Color(255, 255, 255));

        Lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Lable.setForeground(new java.awt.Color(51, 102, 255));
        Lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lable.setText("EMP No.");

        empno_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        empno_textbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empno_textboxMouseClicked(evt);
            }
        });
        empno_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empno_textboxActionPerformed(evt);
            }
        });

        next1_button.setBackground(new java.awt.Color(51, 102, 255));
        next1_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        next1_button.setForeground(new java.awt.Color(255, 255, 255));
        next1_button.setText("next");
        next1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout empno_get_questionLayout = new javax.swing.GroupLayout(empno_get_question);
        empno_get_question.setLayout(empno_get_questionLayout);
        empno_get_questionLayout.setHorizontalGroup(
            empno_get_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empno_get_questionLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empno_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empno_get_questionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(next1_button, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        empno_get_questionLayout.setVerticalGroup(
            empno_get_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empno_get_questionLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(empno_get_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lable)
                    .addComponent(empno_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(next1_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        question_ans.setBackground(new java.awt.Color(255, 255, 255));

        Answer_lable2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Answer_lable2.setForeground(new java.awt.Color(51, 102, 255));
        Answer_lable2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Answer_lable2.setText("Answer");

        answer_textbox2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        answer_textbox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answer_textbox2MouseClicked(evt);
            }
        });
        answer_textbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_textbox2ActionPerformed(evt);
            }
        });

        next1_button3.setBackground(new java.awt.Color(51, 102, 255));
        next1_button3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        next1_button3.setForeground(new java.awt.Color(255, 255, 255));
        next1_button3.setText("next");
        next1_button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1_button3ActionPerformed(evt);
            }
        });

        question_lable2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        question_lable2.setForeground(new java.awt.Color(51, 102, 255));
        question_lable2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        question_lable2.setText("Question");

        question_textarea2.setColumns(20);
        question_textarea2.setRows(5);
        question_textarea2.setEnabled(false);
        jScrollPane3.setViewportView(question_textarea2);

        javax.swing.GroupLayout question_ansLayout = new javax.swing.GroupLayout(question_ans);
        question_ans.setLayout(question_ansLayout);
        question_ansLayout.setHorizontalGroup(
            question_ansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, question_ansLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(next1_button3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(question_ansLayout.createSequentialGroup()
                .addGroup(question_ansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(question_ansLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Answer_lable2))
                    .addGroup(question_ansLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(question_lable2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(question_ansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(answer_textbox2))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        question_ansLayout.setVerticalGroup(
            question_ansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question_ansLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(question_ansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(question_lable2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(question_ansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer_textbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Answer_lable2))
                .addGap(54, 54, 54)
                .addComponent(next1_button3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Set_Password.setBackground(new java.awt.Color(255, 255, 255));
        Set_Password.setPreferredSize(new java.awt.Dimension(550, 400));

        passre_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passre_lable.setForeground(new java.awt.Color(51, 102, 255));
        passre_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passre_lable.setText("Re-enter user-name");

        reenter_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        reenter_textbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reenter_textboxMouseClicked(evt);
            }
        });
        reenter_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reenter_textboxActionPerformed(evt);
            }
        });

        next1_button4.setBackground(new java.awt.Color(51, 102, 255));
        next1_button4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        next1_button4.setForeground(new java.awt.Color(255, 255, 255));
        next1_button4.setText("Submit");
        next1_button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1_button4ActionPerformed(evt);
            }
        });

        username_lable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        username_lable.setForeground(new java.awt.Color(51, 102, 255));
        username_lable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        username_lable.setText("New username");

        username_textbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        username_textbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                username_textboxMouseClicked(evt);
            }
        });
        username_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_textboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Set_PasswordLayout = new javax.swing.GroupLayout(Set_Password);
        Set_Password.setLayout(Set_PasswordLayout);
        Set_PasswordLayout.setHorizontalGroup(
            Set_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Set_PasswordLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(next1_button4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Set_PasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Set_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passre_lable)
                    .addComponent(username_lable))
                .addGap(28, 28, 28)
                .addGroup(Set_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reenter_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        Set_PasswordLayout.setVerticalGroup(
            Set_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Set_PasswordLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(Set_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_lable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(Set_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reenter_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passre_lable))
                .addGap(54, 54, 54)
                .addComponent(next1_button4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        masterpaneLayer.setLayer(empno_get_question, javax.swing.JLayeredPane.DEFAULT_LAYER);
        masterpaneLayer.setLayer(question_ans, javax.swing.JLayeredPane.DEFAULT_LAYER);
        masterpaneLayer.setLayer(Set_Password, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout masterpaneLayerLayout = new javax.swing.GroupLayout(masterpaneLayer);
        masterpaneLayer.setLayout(masterpaneLayerLayout);
        masterpaneLayerLayout.setHorizontalGroup(
            masterpaneLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(empno_get_question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(masterpaneLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(question_ans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(masterpaneLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Set_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );
        masterpaneLayerLayout.setVerticalGroup(
            masterpaneLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(empno_get_question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(masterpaneLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(question_ans, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(masterpaneLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Set_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout masterpaneLayout = new javax.swing.GroupLayout(masterpane);
        masterpane.setLayout(masterpaneLayout);
        masterpaneLayout.setHorizontalGroup(
            masterpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masterpaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(masterpaneLayer)
        );
        masterpaneLayout.setVerticalGroup(
            masterpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterpaneLayout.createSequentialGroup()
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masterpaneLayer))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(masterpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(masterpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void empno_textboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empno_textboxMouseClicked
        // TODO add your handling code here:
        Lable.setForeground(Color.BLUE);
    }//GEN-LAST:event_empno_textboxMouseClicked

    private void empno_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empno_textboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_empno_textboxActionPerformed

    private void next1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1_buttonActionPerformed

        empno = empno_textbox.getText();
        try{
            String sql = "SELECT * FROM `login_employee` WHERE `Emp.no` = '"+empno+"'";
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            boolean c = rs.next();

            if (c){

                empno_get_question.setVisible(false);
                question_ans.setVisible(true);
                Set_Password.setVisible(false);

            }
            else{Lable.setForeground(Color.red);}

        }catch(SQLException e){ System.out.println(e);}

        try{
            String sql = "SELECT * FROM `login_employee` WHERE `Emp.no` = '"+empno+"'";
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
           while(rs.next()){
            question_textarea2.setText(rs.getString("Security_Question"));}
        }catch(SQLException e){ System.out.println(e);}

    }//GEN-LAST:event_next1_buttonActionPerformed

    private void answer_textbox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answer_textbox2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_textbox2MouseClicked

    private void answer_textbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_textbox2ActionPerformed
        // TODO add your handling code here:
        Answer_lable2.setForeground(Color.BLUE);

    }//GEN-LAST:event_answer_textbox2ActionPerformed

    private void next1_button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1_button3ActionPerformed
        // add image of identification that has been scanned
        try{
            String sql = "SELECT * FROM `login_employee` WHERE `Emp.no` = '"+empno+"'";
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
            String ans = rs.getString("Security _Answer");
            if(ans.equals(answer_textbox2.getText()))
            {
                c1.Set_per(true);
                empno_get_question.setVisible(false);
                question_ans.setVisible(false);
                Set_Password.setVisible(true);}
            else{Answer_lable2.setForeground(Color.red);}}
        }catch(SQLException e){ System.out.println(e);}
    }//GEN-LAST:event_next1_button3ActionPerformed

    private void reenter_textboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reenter_textboxMouseClicked
        // TODO add your handling code here:
        username_lable.setForeground(Color.BLUE);
    }//GEN-LAST:event_reenter_textboxMouseClicked

    private void reenter_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reenter_textboxActionPerformed
        // TODO add your handling code here:
        username_lable.setForeground(Color.BLUE);
    }//GEN-LAST:event_reenter_textboxActionPerformed

    private void next1_button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1_button4ActionPerformed

        String username = username_textbox.getText();
        String reenter = reenter_textbox.getText();
        boolean C1 = username.equals("");
        boolean C2 = reenter.equals("");
        boolean C3 = username.equals(reenter);
        if(C1){username_lable.setForeground(Color.red);}
        if(C2){passre_lable.setForeground(Color.red);}
        if(C3==false){username_lable.setForeground(Color.red);passre_lable.setForeground(Color.red);}
        if(C1== false && C2== false && C3==true)
        {

            try{
                String sql = "UPDATE `login_employee` SET `username`='"+username+"'WHERE `Emp.no` ='"+empno+"'";
                PreparedStatement ps = cn.prepareStatement(sql);
                int rs = ps.executeUpdate();
                if(rs >= 0)
                {
                    JOptionPane.showMessageDialog(null,"Submited" );
                    this.dispose();
                }

            }
            catch(SQLException e) {System.out.println(e);JOptionPane.showMessageDialog(null, "There was an error. Please try again.");}

        }

    }//GEN-LAST:event_next1_button4ActionPerformed

    private void username_textboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_username_textboxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_username_textboxMouseClicked

    private void username_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_textboxActionPerformed
        // TODO add your handling code here:

        username_lable.setForeground(Color.BLUE);
    }//GEN-LAST:event_username_textboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(username_forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(username_forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(username_forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(username_forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new username_forgot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Answer_lable2;
    private javax.swing.JLabel Lable;
    private javax.swing.JPanel Set_Password;
    private javax.swing.JTextField answer_textbox2;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel empno_get_question;
    private javax.swing.JTextField empno_textbox;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel masterpane;
    private javax.swing.JLayeredPane masterpaneLayer;
    private javax.swing.JButton next1_button;
    private javax.swing.JButton next1_button3;
    private javax.swing.JButton next1_button4;
    private javax.swing.JLabel passre_lable;
    private javax.swing.JPanel question_ans;
    private javax.swing.JLabel question_lable2;
    private javax.swing.JTextArea question_textarea2;
    private javax.swing.JTextField reenter_textbox;
    private javax.swing.JLabel username_lable;
    private javax.swing.JTextField username_textbox;
    // End of variables declaration//GEN-END:variables
}
